"use client";

import { useEffect, useMemo, useState } from "react";
import PasswordRecovery from "../components/PasswordRecovery";
import { AMAZONAS_MUNICIPALITIES, AMAZONAS_TERRITORIES, getManausZone } from "../data/territories";

const KEY = "cadastro-eleitoral-dainara-2026-v9";
const digits = (v) => String(v || "").replace(/\D/g, "");
const cpfBR = (v) => { const d=digits(v); return d.length===11?d.replace(/(\d{3})(\d{3})(\d{3})(\d{2})/,"$1.$2.$3-$4"):String(v||""); };
const phoneBR = (v) => { const d=digits(v); if(d.length===11)return d.replace(/(\d{2})(\d{5})(\d{4})/,"($1) $2-$3");if(d.length===10)return d.replace(/(\d{2})(\d{4})(\d{4})/,"($1) $2-$3");return String(v||""); };
const cepBR = (v) => { const d=digits(v); return d.length===8?d.replace(/(\d{5})(\d{3})/,"$1-$2"):String(v||""); };
const cpfOK = (v) => { const c=digits(v);if(c.length!==11||/^(\d)\1+$/.test(c))return false;let s=0;for(let i=0;i<9;i++)s+=+c[i]*(10-i);let d=(s*10)%11;if(d===10)d=0;if(d!==+c[9])return false;s=0;for(let i=0;i<10;i++)s+=+c[i]*(11-i);d=(s*10)%11;if(d===10)d=0;return d===+c[10]; };
const empty = { name:"",birth:"",cpf:"",phone:"",address:"",mother:"",email:"",municipality:"",neighborhood:"",manausZone:"",cep:"",title:"",zone:"",section:"" };
const upper = (v) => String(v ?? "").toUpperCase();

function Input({ label,name,value,onChange,numeric=false,maxLength,placeholder,type="text",required=false }) {
  const preserveCase=["email","pix"].includes(name),limits={cpf:11,phone:11,cep:8,title:12,zone:3,section:4},electoral=["title","zone","section"].includes(name);
  return <label className="field"><span>{label}{required?" *":""}</span><input type={type} required={required} value={value||""} placeholder={placeholder} maxLength={maxLength} inputMode={numeric?"numeric":undefined} pattern={electoral?"[0-9]*":undefined} autoCapitalize={preserveCase?"none":undefined} spellCheck={preserveCase?false:undefined} onChange={e=>{let v=e.target.value;if(numeric)v=digits(v).slice(0,limits[name]??maxLength);else if(!preserveCase&&type!=="date")v=upper(v);onChange(v);}}/></label>;
}

function TerritoryFields({ f,setF }) {
  const municipality=f.municipality||"", neighborhoods=municipality?(AMAZONAS_TERRITORIES[municipality]||[]):[],isManaus=municipality==="Manaus",manausZone=isManaus?getManausZone(f.neighborhood||""):"";
  return <><h3>Localização territorial</h3><div className="form-grid three"><label className="field"><span>Município *</span><select required value={municipality} onChange={e=>setF(x=>({...x,municipality:e.target.value,neighborhood:"",manausZone:""}))}><option value="">Selecione o município</option>{AMAZONAS_MUNICIPALITIES.map(m=><option key={m} value={m}>{m}</option>)}</select></label><label className="field"><span>Bairro / localidade *</span><select required disabled={!municipality} value={f.neighborhood||""} onChange={e=>setF(x=>({...x,neighborhood:e.target.value,manausZone:municipality==="Manaus"?getManausZone(e.target.value):""}))}><option value="">{municipality?"Selecione o bairro/localidade":"Selecione primeiro o município"}</option>{neighborhoods.map(b=><option key={b} value={b}>{b}</option>)}</select></label><label className="field"><span>Zona de Manaus</span><input readOnly value={manausZone} placeholder={isManaus?"Detectada automaticamente":"Somente para Manaus"}/></label></div></>;
}

export default function FamiliaPage(){
  const [db,setDb]=useState(null),[leaderId,setLeaderId]=useState(""),[activist,setActivist]=useState(null),[cpf,setCpf]=useState(""),[step,setStep]=useState("loading"),[password,setPassword]=useState(""),[temporaryPassword,setTemporaryPassword]=useState(""),[msg,setMsg]=useState(""),[f,setF]=useState({...empty}),[items,setItems]=useState([]),[editing,setEditing]=useState(null),[search,setSearch]=useState("");
  const request=async(path,options={})=>{const r=await fetch(path,{cache:"no-store",headers:{"Content-Type":"application/json",...(options.headers||{})},...options});const data=await r.json();if(!r.ok)throw Object.assign(new Error(data.error||"Não foi possível concluir a operação."),{data,status:r.status});return data;};
  const loadFamilies=async()=>{const data=await request("/api/families");setItems(data.items||[]);return data.items||[];};

  useEffect(()=>{let live=true;(async()=>{let parsed={leaderships:[]};try{const raw=localStorage.getItem(KEY);if(raw)parsed=JSON.parse(raw);}catch{}if(!live)return;setDb(parsed);const lid=new URLSearchParams(window.location.search).get("lideranca")||"";setLeaderId(lid);if(!lid){setStep("identify");setMsg("Use o link compartilhado pela liderança para iniciar o cadastro.");return;}try{const data=await request("/api/family-access");if(data.activist?.leaderId!==lid){setStep("identify");return;}setActivist(data.activist);setCpf(data.activist.cpf);await loadFamilies();setStep("manage");}catch{if(live)setStep("identify");}})();return()=>{live=false};},[]);

  const identify=async()=>{setMsg("");if(!leaderId)return setMsg("Use o link compartilhado pela liderança para iniciar o cadastro.");if(!cpfOK(cpf))return setMsg("Informe um CPF válido.");try{const data=await request("/api/family-access",{method:"POST",body:JSON.stringify({action:"identify",leadershipId:leaderId,cpf})});setActivist(data.activist);if(data.firstAccess){setTemporaryPassword(data.temporaryPassword);setStep("first-password");}else{setPassword("");setStep("password");}}catch(e){if(e.data?.firstAccess===false)setStep("password");setMsg(e.message);}};
  const login=async()=>{setMsg("");try{const data=await request("/api/family-access",{method:"POST",body:JSON.stringify({action:"login",leadershipId:leaderId,cpf,password})});setActivist(data.activist);await loadFamilies();setStep("manage");}catch(e){setMsg(e.message);}};
  const enterAfterFirstAccess=async()=>{try{await loadFamilies();setTemporaryPassword("");setStep("manage");}catch(e){setMsg(e.message);}};
  const logout=async()=>{try{await request("/api/family-access",{method:"POST",body:JSON.stringify({action:"logout"})});}catch{}setActivist(null);setPassword("");setTemporaryPassword("");setItems([]);setStep("identify");};
  const saveFamily=async(e)=>{e.preventDefault();setMsg("");if(!f.name.trim()||!f.address.trim()||!f.municipality||!f.neighborhood)return setMsg("Informe nome, endereço, município e bairro/localidade.");if(f.cpf&&!cpfOK(f.cpf))return setMsg("O CPF informado é inválido.");try{await request("/api/families",{method:"POST",body:JSON.stringify({action:"save",...f,id:editing?.id})});await loadFamilies();setEditing(null);setF({...empty});setStep("done");}catch(e){setMsg(e.message);}};
  const editFamily=(item)=>{setEditing(item);setF({...empty,...item});setMsg("");setStep("form");};
  const removeFamily=async(item)=>{if(!window.confirm(`Excluir ${item.name} da sua Rede de confiança?`))return;try{await request("/api/families",{method:"POST",body:JSON.stringify({action:"delete",id:item.id})});await loadFamilies();setMsg("Cadastro excluído.");}catch(e){setMsg(e.message);}};
  const leader=useMemo(()=>(db?.leaderships||[]).find(x=>x.id===activist?.leaderId),[db,activist]);
  const title=activist?`REDE DE CONFIANÇA DE ${upper(activist.name)}`:"REDE DE CONFIANÇA";

  if(step==="recovery")return <PasswordRecovery role="activist" initialCpf={cpf} leadershipId={leaderId} onBack={()=>{setPassword("");setMsg("");setStep("identify")}}/>;
  if(step==="loading")return <main className="shell"><section className="card auth-card"><h2>Carregando…</h2></section></main>;
  if(step==="identify")return <main className="shell"><section className="card auth-card"><b>Cadastro Eleitoral</b><h1>Rede de confiança</h1><p>Informe seu CPF de ativista para acessar sua rede.</p><Input label="CPF do ativista" name="cpf" numeric maxLength={11} value={cpf} placeholder="Somente números" onChange={setCpf}/>{msg&&<div className="result">{msg}</div>}<button className="primary" onClick={identify}>Continuar</button><button type="button" className="link-button" disabled={!leaderId} onClick={()=>setStep("recovery")}>Esqueci minha senha</button></section></main>;
  if(step==="password")return <main className="shell"><section className="card auth-card"><button className="back" onClick={()=>{setStep("identify");setMsg("")}}>← Voltar</button><h2>Acesso à Rede de confiança</h2><p>{activist?.name?`${activist.name}, digite sua senha de acesso.`:"Digite a senha fornecida pela coordenação."}</p><label className="field"><span>Senha de acesso</span><input autoFocus type="password" inputMode="numeric" maxLength={8} value={password} onChange={e=>setPassword(digits(e.target.value).slice(0,8))} onKeyDown={e=>e.key==="Enter"&&login()} placeholder="8 números"/></label>{msg&&<div className="result">{msg}</div>}<button className="primary" onClick={login}>Entrar</button><button type="button" className="link-button" onClick={()=>setStep("recovery")}>Esqueci minha senha</button></section></main>;
  if(step==="first-password")return <main className="shell"><section className="card auth-card credential-card"><div className="credential-success">✓ PRIMEIRO ACESSO</div><h2>Senha da Rede de confiança gerada</h2><p>{activist?.name}, guarde esta senha. Nos próximos acessos, ela será solicitada junto com seu CPF.</p><div className="credential-box featured"><div className="credential-item"><span>CPF</span><b>{cpfBR(activist?.cpf)}</b></div><div className="credential-divider"/><div className="credential-item"><span>SENHA DE ACESSO</span><strong>{temporaryPassword}</strong></div><button className="copy-password" onClick={async()=>{try{await navigator.clipboard.writeText(temporaryPassword);setMsg("Senha copiada.");}catch{setMsg("Anote a senha exibida.");}}}>Copiar senha</button></div><div className="credential-warning"><b>Importante:</b> a senha aparece somente agora. Anote ou copie antes de continuar.</div>{msg&&<div className="result">{msg}</div>}<button className="primary" onClick={enterAfterFirstAccess}>Acessar minha rede</button></section></main>;
  if(step==="done")return <main className="shell"><section className="card auth-card"><div className="credential-success">✓ CADASTRO REALIZADO</div><h2>Cadastro concluído</h2><p>Os dados foram salvos na Rede de confiança.</p><button className="primary" onClick={()=>setStep("manage")}>Voltar para minha rede</button></section></main>;
  if(step==="manage"){const filtered=items.filter(item=>`${item.name} ${item.cpf}`.toLowerCase().includes(search.toLowerCase()));return <main className="shell"><section className="card wide"><div className="page-head"><div><h2>Minha Rede de confiança</h2><p>Olá, {activist?.name}. Você pode visualizar e editar somente as pessoas cadastradas em sua rede.</p></div><div className="assessor-actions"><button className="outline" onClick={logout}>Sair</button><button className="primary" onClick={()=>{setEditing(null);setF({...empty});setMsg("");setStep("form")}}>＋ Cadastrar pessoa</button></div></div><input className="search" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar por nome ou CPF..."/>{msg&&<div className="result">{msg}</div>}{filtered.length?filtered.map(item=><div className="list-item" key={item.id}><div><b>{item.name}</b><small>{cpfBR(item.cpf)} • {item.neighborhood||"Sem bairro"}</small></div><div className="assessor-actions"><button className="outline" onClick={()=>editFamily(item)}>Editar</button><button className="danger" onClick={()=>removeFamily(item)}>Excluir</button></div></div>):<div className="empty">Nenhuma pessoa cadastrada nesta rede.</div>}</section></main>}
  return <main className="shell"><section className="card wide"><button className="back" onClick={()=>setStep("manage")}>← Voltar para minha rede</button><h2>{editing?"EDITAR CADASTRO":title}</h2><p>Somente nome, endereço e localização territorial são obrigatórios. Os demais dados podem ser preenchidos quando estiverem disponíveis.</p><div className="context-badge">Liderança responsável: <b>{leader?.name||"Liderança vinculada"}</b></div><form onSubmit={saveFamily}><h3>Dados pessoais</h3><div className="form-grid"><Input label="Nome completo" name="name" value={f.name} required onChange={v=>setF(x=>({...x,name:v}))}/><Input label="Data de nascimento" name="birth" type="date" value={f.birth} onChange={v=>setF(x=>({...x,birth:v}))}/><Input label="CPF" name="cpf" numeric maxLength={11} value={f.cpf} placeholder="Somente números" onChange={v=>setF(x=>({...x,cpf:v}))}/><Input label="Celular / telefone" name="phone" numeric maxLength={11} value={f.phone} placeholder="Somente números" onChange={v=>setF(x=>({...x,phone:v}))}/><Input label="Endereço" name="address" value={f.address} required onChange={v=>setF(x=>({...x,address:v}))}/><Input label="Nome da mãe" name="mother" value={f.mother} onChange={v=>setF(x=>({...x,mother:v}))}/><Input label="E-mail" name="email" type="email" value={f.email} onChange={v=>setF(x=>({...x,email:v}))}/><Input label="CEP" name="cep" numeric maxLength={8} value={f.cep} placeholder="Somente números" onChange={v=>setF(x=>({...x,cep:v}))}/></div><TerritoryFields f={f} setF={setF}/><h3>Dados eleitorais</h3><div className="form-grid three"><Input label="Título de eleitor" name="title" numeric maxLength={12} value={f.title} onChange={v=>setF(x=>({...x,title:v}))}/><Input label="Zona" name="zone" numeric maxLength={3} value={f.zone} onChange={v=>setF(x=>({...x,zone:v}))}/><Input label="Seção" name="section" numeric maxLength={4} value={f.section} onChange={v=>setF(x=>({...x,section:v}))}/></div>{msg&&<div className="result">{msg}</div>}<button className="primary submit">{editing?"Salvar alterações":"Concluir cadastro"}</button></form></section></main>;
}

