"use client";

import { useEffect, useMemo, useState } from "react";

const KEY = "cadastro-eleitoral-dainara-2026-v9";
const digits = (v) => String(v || "").replace(/\D/g, "");
const makeToken = () => globalThis.crypto?.randomUUID?.() || `${Date.now()}-${Math.random()}`;
const cpfBR = (v) => { const d = digits(v); return d.length === 11 ? d.replace(/(\d{3})(\d{3})(\d{3})(\d{2})/, "$1.$2.$3-$4") : String(v || ""); };
const phoneBR = (v) => { const d = digits(v); if (d.length === 11) return d.replace(/(\d{2})(\d{5})(\d{4})/, "($1) $2-$3"); if (d.length === 10) return d.replace(/(\d{2})(\d{4})(\d{4})/, "($1) $2-$3"); return String(v || ""); };
const cepBR = (v) => { const d = digits(v); return d.length === 8 ? d.replace(/(\d{5})(\d{3})/, "$1-$2") : String(v || ""); };
const cpfOK = (v) => { const c = digits(v); if (c.length !== 11 || /^(\d)\1+$/.test(c)) return false; let s=0; for(let i=0;i<9;i++)s+=+c[i]*(10-i); let d=(s*10)%11; if(d===10)d=0; if(d!==+c[9])return false; s=0; for(let i=0;i<10;i++)s+=+c[i]*(11-i); d=(s*10)%11;if(d===10)d=0;return d===+c[10]; };
const empty = { name:"", birth:"", cpf:"", phone:"", address:"", mother:"", email:"", neighborhood:"", cep:"", title:"", zone:"", section:"" };
const upper = (v) => String(v ?? "").toUpperCase();

function Input({ label, name, value, onChange, numeric=false, maxLength, placeholder, type="text", required=false }) {
  return <label className="field"><span>{label}{required ? " *" : ""}</span><input type={type} required={required} value={value || ""} placeholder={placeholder} maxLength={maxLength} inputMode={numeric ? "numeric" : undefined} onChange={e=>{ let v=e.target.value; if(numeric)v=digits(v).slice(0, name==="cpf"?11:name==="phone"?11:name==="cep"?8:name==="title"?12:5); else v=upper(v); onChange(v); }}/></label>;
}

export default function FamiliaPage(){
  const [db,setDb]=useState(null), [leaderId,setLeaderId]=useState(""), [activist,setActivist]=useState(null), [cpf,setCpf]=useState(""), [step,setStep]=useState("loading"), [code,setCode]=useState(""), [expectedCode,setExpectedCode]=useState(""), [msg,setMsg]=useState(""), [f,setF]=useState(empty);
  useEffect(()=>{ try { const raw=localStorage.getItem(KEY); const parsed=raw?JSON.parse(raw):{leaderships:[],activists:[],admins:[],assessors:[]}; setDb(parsed); const lid=new URLSearchParams(window.location.search).get("lideranca")||""; setLeaderId(lid); setStep("identify"); } catch { setDb({leaderships:[],activists:[],admins:[],assessors:[]}); setStep("identify"); } },[]);
  const saveDb=(next)=>{setDb(next);try{localStorage.setItem(KEY,JSON.stringify(next));}catch{}};
  const verifyCpf=()=>{setMsg("");if(!leaderId)return setMsg("Use o link compartilhado pela liderança para iniciar o cadastro.");if(!cpfOK(cpf))return setMsg("Informe um CPF válido.");const a=(db?.activists||[]).find(x=>digits(x.cpf)===digits(cpf)&&x.leaderId===leaderId);if(!a)return setMsg("CPF não reconhecido entre os ativistas desta liderança.");setActivist(a);const generated=String(Math.floor(100000+Math.random()*900000));setExpectedCode(generated);setStep("code");setMsg(`Código de teste enviado para ${phoneBR(a.phone)||"o telefone cadastrado"}.`);};
  const confirmCode=()=>{if(code!==expectedCode)return setMsg("Código incorreto ou expirado.");setMsg("");setF({...empty});setStep("form");};
  const saveFamily=(e)=>{e.preventDefault();setMsg("");if(!f.name.trim())return setMsg("Informe o nome completo.");if(!cpfOK(f.cpf))return setMsg("Informe um CPF válido.");if((db.activists||[]).some(x=>digits(x.cpf)===digits(f.cpf))||(db.families||[]).some(x=>digits(x.cpf)===digits(f.cpf)))return setMsg("Este CPF já possui cadastro no sistema.");const item={...f,name:upper(f.name),mother:upper(f.mother),address:upper(f.address),neighborhood:upper(f.neighborhood),email:upper(f.email),id:globalThis.crypto?.randomUUID?.()||`${Date.now()}-${Math.random()}`,activistId:activist.id,leaderId:activist.leaderId,created:Date.now(),updated:Date.now()};saveDb({...db,families:[...(db.families||[]),item]});setStep("done");};
  const title=useMemo(()=>activist?`REDE DE CONFIANÇA DE ${upper(activist.name)}`:"REDE DE CONFIANÇA",[activist]);
  if(step==="loading")return <main className="shell"><section className="card auth-card"><h2>Carregando…</h2></section></main>;
  if(step==="done")return <main className="shell"><section className="card auth-card"><div className="credential-success">✓ CADASTRO REALIZADO</div><h2>Cadastro concluído</h2><p>Seus dados foram registrados na rede de confiança de <b>{activist?.name}</b>.</p><button className="primary" onClick={()=>{setF(empty);setStep("form")}}>Cadastrar outra pessoa</button></section></main>;
  if(step==="identify")return <main className="shell"><section className="card auth-card"><b>Cadastro Eleitoral</b><h1>Rede de confiança</h1><p>Informe seu CPF de ativista para cadastrar pessoas da rede desta liderança.</p><Input label="CPF do ativista" name="cpf" numeric maxLength={14} value={cpfBR(cpf)} placeholder="000.000.000-00" onChange={setCpf}/>{msg&&<div className="result">{msg}</div>}<button className="primary" onClick={verifyCpf}>Enviar código de acesso</button></section></main>;
  if(step==="code")return <main className="shell"><section className="card auth-card"><h2>Código de acesso</h2><p>Digite o código de 6 dígitos enviado para o telefone cadastrado do ativista.</p><div className="auth-note">Durante o teste, o envio é simulado. Em produção, será integrado ao SMSGo.</div><label className="field"><span>Código</span><input autoFocus inputMode="numeric" maxLength={6} value={code} onChange={e=>setCode(digits(e.target.value).slice(0,6))}/></label>{msg&&<div className="result">{msg}{expectedCode&&<><br/><b>Código de teste: {expectedCode}</b></>}</div>}<button className="primary" onClick={confirmCode}>Validar código</button></section></main>;
  return <main className="shell"><section className="card wide"><button className="back" onClick={()=>setStep("identify")}>← Voltar</button><h2>{title}</h2><p>Cadastre aqui as pessoas que você tem o voto de confiança.</p><div className="context-badge">Ativista responsável: <b>{activist?.name}</b></div><form onSubmit={saveFamily}><h3>Dados pessoais</h3><div className="form-grid"><Input label="Nome completo" name="name" value={f.name} required onChange={v=>setF(x=>({...x,name:v}))}/><Input label="Data de nascimento" name="birth" type="date" value={f.birth} onChange={v=>setF(x=>({...x,birth:v}))}/><Input label="CPF" name="cpf" numeric maxLength={14} value={cpfBR(f.cpf)} required placeholder="000.000.000-00" onChange={v=>setF(x=>({...x,cpf:v}))}/><Input label="Celular / telefone" name="phone" numeric maxLength={15} value={phoneBR(f.phone)} placeholder="(00) 00000-0000" onChange={v=>setF(x=>({...x,phone:v}))}/><Input label="Endereço" name="address" value={f.address} onChange={v=>setF(x=>({...x,address:v}))}/><Input label="Nome da mãe" name="mother" value={f.mother} onChange={v=>setF(x=>({...x,mother:v}))}/><Input label="E-mail" name="email" type="email" value={f.email} onChange={v=>setF(x=>({...x,email:v}))}/><Input label="Bairro" name="neighborhood" value={f.neighborhood} onChange={v=>setF(x=>({...x,neighborhood:v}))}/><Input label="CEP" name="cep" numeric maxLength={9} value={cepBR(f.cep)} placeholder="00000-000" onChange={v=>setF(x=>({...x,cep:v}))}/></div><h3>Dados eleitorais</h3><div className="form-grid three"><Input label="Título de eleitor" name="title" numeric maxLength={12} value={f.title} placeholder="000000000000" onChange={v=>setF(x=>({...x,title:v}))}/><Input label="Zona" name="zone" numeric maxLength={5} value={f.zone} onChange={v=>setF(x=>({...x,zone:v}))}/><Input label="Seção" name="section" numeric maxLength={5} value={f.section} onChange={v=>setF(x=>({...x,section:v}))}/></div>{msg&&<div className="result">{msg}</div>}<button className="primary submit">Concluir cadastro</button></form></section></main>;
}
