"use client";

import { useEffect, useMemo, useState } from "react";
import { AMAZONAS_MUNICIPALITIES, AMAZONAS_TERRITORIES, getManausZone } from "../data/territories";

const KEY = "cadastro-eleitoral-dainara-2026-v9";
const digits = (v) => String(v || "").replace(/\D/g, "");
const makeToken = () => globalThis.crypto?.randomUUID?.() || `${Date.now()}-${Math.random()}`;
const cpfBR = (v) => { const d = digits(v); return d.length === 11 ? d.replace(/(\d{3})(\d{3})(\d{3})(\d{2})/, "$1.$2.$3-$4") : String(v || ""); };
const phoneBR = (v) => { const d = digits(v); if (d.length === 11) return d.replace(/(\d{2})(\d{5})(\d{4})/, "($1) $2-$3"); if (d.length === 10) return d.replace(/(\d{2})(\d{4})(\d{4})/, "($1) $2-$3"); return String(v || ""); };
const cepBR = (v) => { const d = digits(v); return d.length === 8 ? d.replace(/(\d{5})(\d{3})/, "$1-$2") : String(v || ""); };
const cpfOK = (v) => { const c = digits(v); if (c.length !== 11 || /^(\d)\1+$/.test(c)) return false; let s=0; for(let i=0;i<9;i++)s+=+c[i]*(10-i); let d=(s*10)%11; if(d===10)d=0; if(d!==+c[9])return false; s=0; for(let i=0;i<10;i++)s+=+c[i]*(11-i); d=(s*10)%11;if(d===10)d=0;return d===+c[10]; };
const empty = { name:"", birth:"", cpf:"", phone:"", address:"", mother:"", email:"", municipality:"", neighborhood:"", manausZone:"", cep:"", title:"", zone:"", section:"" };
const upper = (v) => String(v ?? "").toUpperCase();

function Input({ label, name, value, onChange, numeric=false, maxLength, placeholder, type="text", required=false }) {
  const preserveCase = ["email", "pix"].includes(name);
  const limits = { cpf: 11, phone: 11, cep: 8, title: 12, zone: 3, section: 4 };
  const electoral = ["title", "zone", "section"].includes(name);
  return <label className="field"><span>{label}{required ? " *" : ""}</span><input type={type} required={required} value={value || ""} placeholder={placeholder} maxLength={maxLength} inputMode={numeric ? "numeric" : undefined} pattern={electoral ? "[0-9]*" : undefined} autoCapitalize={preserveCase ? "none" : undefined} spellCheck={preserveCase ? false : undefined} onChange={e=>{ let v=e.target.value; if(numeric)v=digits(v).slice(0, limits[name] ?? maxLength); else if(!preserveCase && type!=="date")v=upper(v); onChange(v); }}/></label>;
}

function TerritoryFields({ f, setF }) {
  const municipality = f.municipality || "";
  const neighborhoods = municipality ? (AMAZONAS_TERRITORIES[municipality] || []) : [];
  const isManaus = municipality === "Manaus";
  const manausZone = isManaus ? getManausZone(f.neighborhood || "") : "";
  return <><h3>Localização territorial</h3><div className="form-grid three"><label className="field"><span>Município *</span><select required value={municipality} onChange={e=>setF(x=>({...x,municipality:e.target.value,neighborhood:"",manausZone:""}))}><option value="">Selecione o município</option>{AMAZONAS_MUNICIPALITIES.map(m=><option key={m} value={m}>{m}</option>)}</select></label><label className="field"><span>Bairro / localidade *</span><select required disabled={!municipality} value={f.neighborhood || ""} onChange={e=>setF(x=>({...x,neighborhood:e.target.value,manausZone:municipality==="Manaus"?getManausZone(e.target.value):""}))}><option value="">{municipality ? "Selecione o bairro/localidade" : "Selecione primeiro o município"}</option>{neighborhoods.map(b=><option key={b} value={b}>{b}</option>)}</select></label><label className="field"><span>Zona de Manaus</span><input readOnly value={manausZone} placeholder={isManaus ? "Detectada automaticamente" : "Somente para Manaus"}/></label></div></>;
}

export default function FamiliaPage(){
  const [db,setDb]=useState(null), [leaderId,setLeaderId]=useState(""), [activist,setActivist]=useState(null), [cpf,setCpf]=useState(""), [step,setStep]=useState("loading"), [code,setCode]=useState(""), [challengeId,setChallengeId]=useState(""), [msg,setMsg]=useState(""), [f,setF]=useState(empty);
  useEffect(()=>{ try { const raw=localStorage.getItem(KEY); const parsed=raw?JSON.parse(raw):{leaderships:[],activists:[],admins:[],assessors:[],families:[]}; setDb(parsed); const lid=new URLSearchParams(window.location.search).get("lideranca")||""; setLeaderId(lid); setStep("identify"); } catch { setDb({leaderships:[],activists:[],admins:[],assessors:[],families:[]}); setStep("identify"); } },[]);
  const saveDb=(next)=>{setDb(next);try{localStorage.setItem(KEY,JSON.stringify(next));}catch{}};
  const verifyCpf=async()=>{setMsg("");if(!leaderId)return setMsg("Use o link compartilhado pela liderança para iniciar o cadastro.");if(!cpfOK(cpf))return setMsg("Informe um CPF válido.");setMsg("Enviando código por SMS…");try{const r=await fetch("/api/sms",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"send-family-code",leadershipId:leaderId,cpf})});const data=await r.json();if(!r.ok)throw new Error(data.error||"Não foi possível enviar o SMS.");const a=(db?.activists||[]).find(x=>digits(x.cpf)===digits(cpf)&&x.leaderId===leaderId)||{cpf,leaderId};setActivist(a);setChallengeId(data.challengeId);setStep("code");setMsg("Código enviado por SMS para o telefone cadastrado do ativista.");}catch(e){setMsg(e.message);}};
  const confirmCode=async()=>{setMsg("");try{const r=await fetch("/api/sms",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"verify-family-code",challengeId,code})});const data=await r.json();if(!r.ok)throw new Error(data.error||"Código incorreto ou expirado.");setF({...empty});setStep("form");}catch(e){setMsg(e.message);}};
  const saveFamily=(e)=>{e.preventDefault();setMsg("");if(!f.name.trim())return setMsg("Informe o nome completo.");if(!cpfOK(f.cpf))return setMsg("Informe um CPF válido.");if((db.activists||[]).some(x=>digits(x.cpf)===digits(f.cpf))||(db.families||[]).some(x=>digits(x.cpf)===digits(f.cpf)))return setMsg("Este CPF já possui cadastro no sistema.");const item={...f,name:upper(f.name),mother:upper(f.mother),address:upper(f.address),neighborhood:upper(f.neighborhood),email:String(f.email||"").trim(),title:digits(f.title).slice(0,12),zone:digits(f.zone).slice(0,3),section:digits(f.section).slice(0,4),id:globalThis.crypto?.randomUUID?.()||`${Date.now()}-${Math.random()}`,activistId:activist.id,leaderId:activist.leaderId,created:Date.now(),updated:Date.now()};saveDb({...db,families:[...(db.families||[]),item]});setStep("done");};
  const leader=useMemo(()=>(db?.leaderships||[]).find(x=>x.id===activist?.leaderId),[db,activist]);
  const title=useMemo(()=>activist?`REDE DE CONFIANÇA DE ${upper(activist.name)}`:"REDE DE CONFIANÇA",[activist]);
  if(step==="loading")return <main className="shell"><section className="card auth-card"><h2>Carregando…</h2></section></main>;
  if(step==="done")return <main className="shell"><section className="card auth-card"><div className="credential-success">✓ CADASTRO REALIZADO</div><h2>Cadastro concluído</h2><p>Seus dados foram registrados na rede de confiança de <b>{activist?.name}</b>.</p><button className="primary" onClick={()=>{setF(empty);setStep("form")}}>Cadastrar outra pessoa</button></section></main>;
  if(step==="identify")return <main className="shell"><section className="card auth-card"><b>Cadastro Eleitoral</b><h1>Rede de confiança</h1><p>Informe seu CPF de ativista para cadastrar pessoas da rede desta liderança.</p><Input label="CPF do ativista" name="cpf" numeric maxLength={14} value={cpfBR(cpf)} placeholder="000.000.000-00" onChange={setCpf}/>{msg&&<div className="result">{msg}</div>}<button className="primary" onClick={verifyCpf}>Enviar código de acesso</button></section></main>;
  if(step==="code")return <main className="shell"><section className="card auth-card"><h2>Código de acesso</h2><p>Digite o código de 6 dígitos enviado para o telefone cadastrado do ativista.</p><div className="auth-note">Um código de 6 dígitos foi enviado por SMS para o telefone cadastrado do ativista. Ele expira em 5 minutos.</div><label className="field"><span>Código</span><input autoFocus inputMode="numeric" maxLength={6} value={code} onChange={e=>setCode(digits(e.target.value).slice(0,6))}/></label>{msg&&<div className="result">{msg}</div>}<button className="primary" onClick={confirmCode}>Validar código</button></section></main>;
  return <main className="shell"><section className="card wide"><button className="back" onClick={()=>setStep("identify")}>← Voltar</button><h2>{title}</h2><p>Cadastre aqui as pessoas que você tem o voto de confiança.</p><div className="context-badge">Liderança responsável: <b>{leader?.name || "Não localizada"}</b></div><form onSubmit={saveFamily}><h3>Dados pessoais</h3><div className="form-grid"><Input label="Nome completo" name="name" value={f.name} required onChange={v=>setF(x=>({...x,name:v}))}/><Input label="Data de nascimento" name="birth" type="date" value={f.birth} onChange={v=>setF(x=>({...x,birth:v}))}/><Input label="CPF" name="cpf" numeric maxLength={14} value={cpfBR(f.cpf)} required placeholder="000.000.000-00" onChange={v=>setF(x=>({...x,cpf:v}))}/><Input label="Celular / telefone" name="phone" numeric maxLength={15} value={phoneBR(f.phone)} placeholder="(00) 00000-0000" onChange={v=>setF(x=>({...x,phone:v}))}/><Input label="Endereço" name="address" value={f.address} onChange={v=>setF(x=>({...x,address:v}))}/><Input label="Nome da mãe" name="mother" value={f.mother} onChange={v=>setF(x=>({...x,mother:v}))}/><Input label="E-mail" name="email" type="email" value={f.email} onChange={v=>setF(x=>({...x,email:v}))}/><Input label="CEP" name="cep" numeric maxLength={9} value={cepBR(f.cep)} placeholder="00000-000" onChange={v=>setF(x=>({...x,cep:v}))}/></div><TerritoryFields f={f} setF={setF}/><h3>Dados eleitorais</h3><div className="form-grid three"><Input label="Título de eleitor" name="title" numeric maxLength={12} value={f.title} placeholder="000000000000" onChange={v=>setF(x=>({...x,title:v}))}/><Input label="Zona" name="zone" numeric maxLength={3} value={f.zone} onChange={v=>setF(x=>({...x,zone:v}))}/><Input label="Seção" name="section" numeric maxLength={4} value={f.section} onChange={v=>setF(x=>({...x,section:v}))}/></div>{msg&&<div className="result">{msg}</div>}<button className="primary submit">Concluir cadastro</button></form></section></main>;
}
