"use client";
import { useEffect, useMemo, useState } from "react";
import { addRecord, getData, updateRecord } from "../lib/storage";
import { digits, isPlausibleTitle, isValidCPF } from "../lib/validation";
const CODE="328974",TSE="https://www.tse.jus.br/servicos-eleitorais/autoatendimento-eleitoral";
const blank={name:"",birthDate:"",cpf:"",phone:"",address:"",motherName:"",email:"",neighborhood:"",zip:"",title:"",zone:"",section:"",pix:"",holder:"",bank:"",leaderName:""};
const cpf=v=>{const n=digits(v).slice(0,11);return n.replace(/(\d{3})(\d)/,"$1.$2").replace(/(\d{3})(\d)/,"$1.$2").replace(/(\d{3})(\d{1,2})$/,"$1-$2")};
export default function Page(){
 const[mode,setMode]=useState("home"),[data,setData]=useState({leaders:[],activists:[],admins:[]}),[login,setLogin]=useState({cpf:"",title:"",code:""}),[release,setRelease]=useState(""),[notice,setNotice]=useState(""),[person,setPerson]=useState(blank),[role,setRole]=useState(""),[current,setCurrent]=useState(null),[search,setSearch]=useState("");
 useEffect(()=>setData(getData()),[]); const go=m=>{setMode(m);setNotice("");setRelease("");setLogin({cpf:"",title:"",code:""})}; const valid=()=>person.name.trim()&&isValidCPF(person.cpf)&&isPlausibleTitle(person.title);
 const unlock=k=>{if(release!==CODE)return setNotice("Código de liberação inválido.");setPerson(blank);go(k==="admin"?"adminRegister":"leaderRegister")};
 const enter=k=>{if(login.code!==CODE)return setNotice("Informe o código de teste 328974 para entrar.");if(!isValidCPF(login.cpf))return setNotice("Informe um CPF válido para o teste.");if(!isPlausibleTitle(login.title))return setNotice("Informe os 8 dígitos do título de eleitor.");setRole(k);go(k==="admin"?"adminDash":"leaderDash")};
 const save=k=>{if(!valid())return setNotice("Preencha nome, CPF válido e os 8 dígitos do título.");const type=k==="admin"?"admins":k==="activist"?"activists":"leaders";const value=k==="activist"?{...person,leaderName:role==="leader"?"Liderança de teste":person.leaderName||"Liderança de teste"}:person;setData(addRecord(type,value));go(k==="admin"?"adminDash":k==="leader"?"leaderDash":role==="admin"?"adminDash":"leaderDash")};
 const add=k=>{setPerson({...blank,leaderName:k==="activist"&&role==="leader"?"Liderança de teste":""});go(k==="activist"?"activistRegister":"leaderRegister")};
 const open=(type,item)=>{setCurrent({type,item});go("detail")}; const filtered=t=>data[t].filter(x=>`${x.name} ${x.cpf} ${x.leaderName||""}`.toLowerCase().includes(search.toLowerCase()));
 const exportCsv=()=>{const rows=[["Tipo","Nome","CPF","Telefone","E-mail","Título","Zona","Seção","Liderança responsável"]];data.leaders.forEach(x=>rows.push(["Liderança",x.name,x.cpf,x.phone,x.email,x.title,x.zone,x.section,""]));data.activists.forEach(x=>rows.push(["Ativista",x.name,x.cpf,x.phone,x.email,x.title,x.zone,x.section,x.leaderName||""]));const csv=rows.map(r=>r.map(x=>`"${String(x||"").replaceAll('"','""')}"`).join(";")).join("\n"),url=URL.createObjectURL(new Blob(["\ufeff"+csv],{type:"text/csv;charset=utf-8"})),a=document.createElement("a");a.href=url;a.download="cadastro-eleitoral.csv";a.click();URL.revokeObjectURL(url)};
 if(mode==="home")return <Home go={go}/>;
 if(["leaderLogin","adminLogin"].includes(mode))return <Login admin={mode==="adminLogin"} value={login} set={setLogin} notice={notice} back={()=>go("home")} enter={enter}/>;
 if(["leaderRelease","adminRelease"].includes(mode))return <Release admin={mode==="adminRelease"} value={release} set={setRelease} notice={notice} back={()=>go("home")} unlock={unlock}/>;
 if(["leaderRegister","adminRegister","activistRegister"].includes(mode)){const k=mode==="adminRegister"?"admin":mode==="activistRegister"?"activist":"leader";return <Form kind={k} person={person} set={setPerson} leaders={data.leaders} notice={notice} back={()=>go(role==="admin"?"adminDash":"home")} save={save}/>}
 if(mode==="detail"&&current)return <Detail rec={current} data={data} back={()=>go(role==="admin"?"adminDash":"leaderDash")} open={open} edit={()=>{setPerson(current.item);go("edit")}}/>;
 if(mode==="edit"&&current)return <Form kind={current.type==="leaders"?"leader":current.type==="admins"?"admin":"activist"} person={person} set={setPerson} leaders={data.leaders} notice={notice} editing back={()=>go("detail")} save={()=>{if(!valid())return setNotice("Preencha nome, CPF válido e os 8 dígitos do título.");const d=updateRecord(current.type,current.item.id,person);setData(d);setCurrent({type:current.type,item:d[current.type].find(x=>x.id===current.item.id)});go("detail")}}/>;
 const admin=role==="admin",acts=admin?filtered("activists"):filtered("activists").filter(x=>x.leaderName==="Liderança de teste");return <Dashboard admin={admin} data={data} leaders={filtered("leaders")} acts={acts} search={search} setSearch={setSearch} go={()=>go("home")} add={add} open={open} exportCsv={exportCsv}/>;
}
function Home({go}){return <main className="shell"><section className="hero"><span className="eyebrow">Portal de acesso e cadastro</span><h1>Cadastro Eleitoral</h1><h2>Coordenadora Dainara Torres</h2><p>Organize lideranças, equipes e ativistas em um só lugar.</p><div className="actions"><button onClick={()=>go("leaderLogin")}>Já sou liderança</button><button onClick={()=>go("leaderRelease")}>Se torne liderança</button><button className="outline" onClick={()=>go("adminLogin")}>Acesso administrativo</button><button className="outline" onClick={()=>go("adminRelease")}>Se tornar administrador</button></div><small>Ambiente de teste — código: 328974</small></section></main>}
function Login({admin,value,set,notice,back,enter}){return <Card title={admin?"Acesso administrativo":"Área da liderança"} text="Para o teste, informe seus dados e o código de acesso." back={back}><Field label="CPF" value={value.cpf} set={v=>set({...value,cpf:cpf(v)})} placeholder="000.000.000-00"/><Field label="8 dígitos do título" value={value.title} set={v=>set({...value,title:digits(v).slice(0,8)})} placeholder="00000000"/><Field label="Código de teste" value={value.code} set={v=>set({...value,code:digits(v).slice(0,6)})} placeholder="328974"/><button onClick={()=>enter(admin?"admin":"leader")}>Entrar</button><Notice text={notice}/></Card>}
function Release({admin,value,set,notice,back,unlock}){return <Card title={admin?"Se tornar administrador":"Se torne liderança"} text="Informe o código de liberação para iniciar o cadastro." back={back}><Field label="Código de liberação" value={value} set={v=>set(digits(v).slice(0,6))} placeholder="000000"/><button onClick={()=>unlock(admin?"admin":"leader")}>Liberar cadastro</button><Notice text={notice}/></Card>}
function Form({kind,person,set,leaders,notice,back,save,editing}){const field=(key,label,props={})=><Field key={key} label={label} value={person[key]||""} set={v=>set({...person,[key]:key==="cpf"?cpf(v):key==="title"?digits(v).slice(0,8):v})} {...props}/>;const label=kind==="admin"?"administrador":kind==="activist"?"ativista":"liderança";return <Card wide title={`${editing?"Editar":"Cadastro de"} ${label}`} text="Preencha os dados para o ambiente de teste." back={back}><div className="form-grid">{field("name","Nome completo")}{field("birthDate","Data de nascimento",{type:"date"})}{field("cpf","CPF",{placeholder:"000.000.000-00"})}{field("phone","Telefone")}{field("email","E-mail",{type:"email"})}{field("motherName","Nome da mãe")}{field("address","Endereço")}{field("neighborhood","Bairro")}{field("zip","CEP")}{field("title","8 dígitos do título",{placeholder:"00000000"})}{field("zone","Zona")}{field("section","Seção")}{field("pix","Chave Pix")}{field("holder","Nome do titular")}{field("bank","Banco")}{kind==="activist"&&<label>Liderança responsável<select value={person.leaderName||""} onChange={e=>set({...person,leaderName:e.target.value})}><option value="">Liderança de teste</option>{leaders.map(x=><option key={x.id} value={x.name}>{x.name}</option>)}</select></label>}</div>{kind!=="admin"&&<p className="tse"><a href={TSE} target="_blank" rel="noreferrer">Consultar situação no TSE ↗</a></p>}<button onClick={()=>save(kind)}>{editing?"Salvar alterações":"Salvar cadastro"}</button><Notice text={notice}/></Card>}
function Dashboard({admin,data,leaders,acts,search,setSearch,go,add,open,exportCsv}){return <main className="shell dashboard"><header><div><span className="eyebrow">Acesso de teste</span><h1>{admin?"Área Administrativa":"Área da Liderança"}</h1><p>{admin?"Visão geral das lideranças e equipes.":"Sua equipe e seus ativistas vinculados."}</p></div><button className="outline" onClick={go}>Sair</button></header><section className="metrics"><Metric label="Lideranças" value={admin?data.leaders.length:1}/><Metric label="Ativistas" value={acts.length}/><Metric label="Equipes" value={admin?data.leaders.length:1}/></section><section className="panel toolbar"><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Pesquisar por nome, CPF ou liderança…"/><button onClick={()=>add("activist")}>+ Adicionar ativista</button>{admin&&<><button className="outline" onClick={()=>add("leader")}>+ Liderança</button><button className="outline" onClick={exportCsv}>Exportar CSV</button></>}</section>{admin&&<List title="Lideranças cadastradas" rows={leaders} open={x=>open("leaders",x)} empty="Nenhuma liderança cadastrada ainda."/>}{admin&&<Team leaders={data.leaders} acts={data.activists}/>}<List title={admin?"Todos os ativistas":"Ativistas da sua equipe"} rows={acts} active open={x=>open("activists",x)} empty="Nenhum ativista cadastrado ainda."/></main>}
function Detail({rec,data,back,open,edit}){const x=rec.item,team=rec.type==="leaders"?data.activists.filter(a=>a.leaderName===x.name):[];return <Card wide title={x.name} text={rec.type==="leaders"?"Liderança":rec.type==="activists"?"Ativista":"Administrador"} back={back}><button onClick={edit}>Editar cadastro</button><div className="details">{[["CPF",x.cpf],["Telefone",x.phone],["E-mail",x.email],["Endereço",x.address],["Título",x.title],["Zona / Seção",`${x.zone||"—"} / ${x.section||"—"}`],["Pix",x.pix],["Banco",x.bank],...(rec.type==="activists"?[["Liderança responsável",x.leaderName||"Liderança de teste"]]:[])].map(([a,b])=><div key={a}><strong>{a}</strong><span>{b||"—"}</span></div>)}</div>{rec.type==="leaders"&&<List title={`Ativistas vinculados (${team.length})`} rows={team} active open={x=>open("activists",x)} empty="Nenhum ativista vinculado."/>}</Card>}
function Team({leaders,acts}){return <section className="panel"><h2>Quantidade por liderança</h2>{leaders.length?<div className="records">{leaders.map(x=><div className="record static" key={x.id}><strong>{x.name}</strong><small>{acts.filter(a=>a.leaderName===x.name).length} ativista(s)</small></div>)}</div>:<p className="muted">Cadastre uma liderança para acompanhar as equipes.</p>}</section>}
function List({title,rows,open,empty,active}){return <section className="panel"><h2>{title}</h2>{rows.length?<div className="records">{rows.map(x=><button className="record" key={x.id} onClick={()=>open(x)}><div><strong>{x.name}</strong><span>{x.cpf||"Cadastro de teste"}</span></div>{active&&<small>{x.leaderName||"Liderança de teste"}</small>}<b>Ver →</b></button>)}</div>:<p className="muted">{empty}</p>}</section>}
function Card({title,text,children,back,wide}){return <main className="shell"><section className={`card ${wide?"wide":""}`}><button className="back" onClick={back}>← Voltar</button><span className="eyebrow">Cadastro Eleitoral</span><h1>{title}</h1><p>{text}</p><div className="grid">{children}</div></section></main>};function Field({label,value,set,...props}){return <label>{label}<input value={value} onChange={e=>set(e.target.value)} inputMode={props.type?undefined:"numeric"} {...props}/></label>};function Notice({text}){return text?<div className="notice">{text}</div>:null};function Metric({label,value}){return <div className="metric"><strong>{value}</strong><span>{label}</span></div>}
