"use client";

import { useEffect, useMemo, useState } from "react";

const CODE = "328974";
const TSE = "https://www.tse.jus.br/servicos-eleitorais/autoatendimento-eleitoral";
const KEY = "cadastro-eleitoral-dainara-2026-v7";
const EMPTY = { name:"", birth:"", cpf:"", phone:"", address:"", mother:"", email:"", neighborhood:"", cep:"", title:"", zone:"", section:"", pix:"", pixname:"", bank:"" };
const digits = v => String(v || "").replace(/\D/g, "");
const makeId = () => globalThis.crypto?.randomUUID?.() || `${Date.now()}-${Math.random()}`;
const cpfOK = v => { const c=digits(v); if(c.length!==11 || /^(\d)\1+$/.test(c)) return false; let s=0; for(let i=0;i<9;i++) s += +c[i]*(10-i); let d=s*10%11; if(d===10)d=0; if(d!==+c[9])return false; s=0; for(let i=0;i<10;i++)s += +c[i]*(11-i); d=s*10%11; if(d===10)d=0; return d===+c[10]; };
const titleOK = v => digits(v).length === 12;
const dateBR = v => v ? String(v).split("-").reverse().join("/") : "";
const cpfBR = v => { const d=digits(v); return d.length===11 ? d.replace(/(\d{3})(\d{3})(\d{3})(\d{2})/,"$1.$2.$3-$4") : String(v||""); };
const cepBR = v => { const d=digits(v); return d.length===8 ? d.replace(/(\d{5})(\d{3})/,"$1-$2") : String(v||""); };
const phoneBR = v => { const d=digits(v); if(d.length===11)return d.replace(/(\d{2})(\d{5})(\d{4})/,"($1) $2-$3"); if(d.length===10)return d.replace(/(\d{2})(\d{4})(\d{4})/,"($1) $2-$3"); return String(v||""); };
const fresh = () => ({leaderships:[],activists:[],admins:[],assessors:[{id:"a1",name:"Assessoria da Coordenadora",phone:"Contato cadastrado pela administração",email:"Contato interno"}]});

function maskField(n,v){
  const d=digits(v);
  if(n==="cpf") return cpfBR(d);
  if(n==="phone") return phoneBR(d);
  if(n==="cep") return cepBR(d);
  if(n==="title") return d.slice(0,12);
  if(n==="zone"||n==="section") return d;
  return String(v||"");
}
function Field({f,setF,n,label,type="text",required=false,placeholder}){
  const numeric=["cpf","phone","cep","title","zone","section"].includes(n);
  const max={cpf:14,phone:15,cep:9,title:12,zone:5,section:5}[n];
  return <label className="field"><span>{label}{required?" *":""}</span><input type={type} required={required} value={numeric?maskField(n,f[n]):(f[n]||"")} placeholder={placeholder} maxLength={max} inputMode={numeric?"numeric":undefined} onChange={e=>{let v=e.target.value;if(numeric)v=digits(v).slice(0,n==="cpf"?11:n==="phone"?11:n==="cep"?8:n==="title"?12:5);setF(x=>({...x,[n]:v}))}}/></label>
}
function Form({kind,f,setF,save,back,msg,edit}){ return <main className="shell"><section className="card wide"><button className="back" onClick={back}>← Voltar</button><h2>{edit?`Editar ${kind}`:`Cadastro de ${kind}`}</h2><p>Preencha os dados e salve o cadastro.</p><form onSubmit={save}><h3>Dados pessoais</h3><div className="form-grid"><Field f={f} setF={setF} n="name" label="Nome completo" required/><Field f={f} setF={setF} n="birth" label="Data de nascimento" type="date"/><Field f={f} setF={setF} n="cpf" label="CPF" required placeholder="000.000.000-00"/><Field f={f} setF={setF} n="phone" label="Celular / telefone" placeholder="(00) 00000-0000"/><Field f={f} setF={setF} n="address" label="Endereço"/><Field f={f} setF={setF} n="mother" label="Nome da mãe"/><Field f={f} setF={setF} n="email" label="E-mail" type="email"/><Field f={f} setF={setF} n="neighborhood" label="Bairro"/><Field f={f} setF={setF} n="cep" label="CEP" placeholder="00000-000"/></div><h3>Dados eleitorais</h3><div className="form-grid three"><Field f={f} setF={setF} n="title" label="Título de eleitor" required placeholder="000000000000"/><Field f={f} setF={setF} n="zone" label="Zona"/><Field f={f} setF={setF} n="section" label="Seção"/></div><div className="validation-row"><button type="button" className="outline" onClick={()=>setF(x=>({...x,_validation:`${cpfOK(x.cpf)?"✓ CPF válido":"✗ CPF inválido"} • ${titleOK(x.title)?"✓ Título válido":"✗ Título inválido"}`}))}>Validar CPF e título</button><a className="tse" href={TSE} target="_blank" rel="noreferrer">Consultar situação no TSE ↗</a></div><h3>Dados de pagamento</h3><div className="form-grid three"><Field f={f} setF={setF} n="pix" label="Chave Pix"/><Field f={f} setF={setF} n="pixname" label="Nome do titular"/><Field f={f} setF={setF} n="bank" label="Banco"/></div>{f._validation&&<div className="result">{f._validation}</div>}{msg&&<div className="result">{msg}</div>}<button className="primary submit">{edit?"Salvar alterações":`Cadastrar ${kind}`}</button></form></section></main> }
function Access({admin,release,code,setCode,msg,onEnter,onBack,onSwitch}){ return <main className="shell"><section className="card auth-card"><button className="back" onClick={onBack}>← Voltar</button><h2>{release?(admin?"Se tornar administrador":"Se torne liderança"):(admin?"Acesso administrativo":"Já sou liderança")}</h2><p>{release?"Informe o código de liberação para continuar.":admin?"Acesse a gestão centralizada de lideranças e ativistas.":"Acesse somente sua equipe e seus ativistas vinculados."}</p><label className="field"><span>Código de acesso</span><input autoFocus inputMode="numeric" maxLength={6} value={code} placeholder="000000" onChange={e=>setCode(digits(e.target.value).slice(0,6))} onKeyDown={e=>e.key==="Enter"&&onEnter()}/></label><button className="primary" onClick={onEnter}>{release?"Continuar":"Entrar"}</button>{msg&&<div className="result">{msg}</div>}<div className="auth-note">Código de teste: <b>328974</b></div><button className="link-button" onClick={onSwitch}>{release?(admin?"Voltar ao acesso administrativo":"Já sou liderança"):(admin?"Se tornar administrador":"Se torne liderança")}</button></section></main> }
function AdminReg({back,save,msg}){ return <main className="shell"><section className="card auth-card"><button className="back" onClick={back}>← Voltar</button><h2>Se tornar administrador</h2><p>Cadastro liberado pelo código de teste.</p><form onSubmit={save}><label className="field"><span>Nome completo *</span><input name="name" required/></label><label className="field"><span>CPF *</span><input name="cpf" required maxLength={14} inputMode="numeric" placeholder="000.000.000-00" onChange={e=>{e.currentTarget.value=cpfBR(e.currentTarget.value)}}/></label><label className="field"><span>E-mail</span><input name="email" type="email"/></label>{msg&&<div className="result">{msg}</div>}<button className="primary">Concluir cadastro</button></form></section></main> }
function Detail({person,title,leader,onBack,onEdit,team}){ if(!person)return <main className="shell"><section className="card"><button className="back" onClick={onBack}>← Voltar</button><div className="empty">Cadastro não encontrado.</div></section></main>; return <main className="shell"><section className="card wide"><div className="page-head"><div><button className="back" onClick={onBack}>← Voltar</button><h2>{title}</h2></div><button className="primary" onClick={onEdit}>Editar cadastro</button></div>{leader&&<div className="context-badge">Liderança: <b>{leader}</b></div>}<div className="detail-grid"><div className="panel"><h3>Dados pessoais</h3><p><b>Nome:</b> {person.name}</p><p><b>Nascimento:</b> {dateBR(person.birth)||"—"}</p><p><b>CPF:</b> {cpfBR(person.cpf)||"—"}</p><p><b>Telefone:</b> {phoneBR(person.phone)||"—"}</p><p><b>E-mail:</b> {person.email||"—"}</p><p><b>Nome da mãe:</b> {person.mother||"—"}</p><p><b>Endereço:</b> {person.address||"—"}</p><p><b>Bairro:</b> {person.neighborhood||"—"}</p><p><b>CEP:</b> {cepBR(person.cep)||"—"}</p></div><div className="panel"><h3>Dados eleitorais</h3><p><b>Título:</b> {person.title||"—"}</p><p><b>Zona:</b> {person.zone||"—"}</p><p><b>Seção:</b> {person.section||"—"}</p><h3>Dados de pagamento</h3><p><b>Pix:</b> {person.pix||"—"}</p><p><b>Titular:</b> {person.pixname||"—"}</p><p><b>Banco:</b> {person.bank||"—"}</p></div></div>{team}</section></main> }
function Side({admin,view,setView,logout,newL,newA,exportExcel,exportCSV}){ return <aside className="sidebar"><div className="brand"><b>Cadastro Eleitoral</b><span>{admin?"Coordenadora Dainara Torres":"Área da liderança"}</span></div><div className="nav-title">Menu</div><nav><button className={view==="dashboard"?"active":""} onClick={()=>setView("dashboard")}>⌂ Dashboard</button>{admin?<><button className={view==="leaderships"?"active":""} onClick={()=>setView("leaderships")}>♙ Lideranças</button><button className={view==="activists"?"active":""} onClick={()=>setView("activists")}>♧ Ativistas</button><button className={view==="admins"?"active":""} onClick={()=>setView("admins")}>◉ Administradores</button><button onClick={newL}>＋ Nova liderança</button></>:<><button className={view==="activists"?"active":""} onClick={()=>setView("activists")}>♧ Meus ativistas</button><button onClick={newA}>＋ Adicionar ativista</button><button className={view==="profile"?"active":""} onClick={()=>setView("profile")}>👤 Meu cadastro</button><button className={view==="assessors"?"active":""} onClick={()=>setView("assessors")}>☎ Contatos da assessoria</button></>}</nav>{admin&&<><button className="export-side" onClick={exportExcel}>⇩ Exportar Excel</button><button className="export-side" onClick={exportCSV}>⇩ Exportar CSV</button></>}<button className="logout" onClick={logout}>Sair</button></aside> }

export default function Portal(){
 const [mode,setMode]=useState("home"),[code,setCode]=useState(""),[msg,setMsg]=useState(""),[f,setF]=useState(EMPTY),[db,setDb]=useState(fresh()),[role,setRole]=useState(null),[leaderId,setLeaderId]=useState(null),[view,setView]=useState("dashboard"),[search,setSearch]=useState(""),[detail,setDetail]=useState(null),[editing,setEditing]=useState(null),[returnTo,setReturnTo]=useState("home");
 useEffect(()=>{try{const raw=localStorage.getItem(KEY);if(raw)setDb({...fresh(),...JSON.parse(raw)})}catch(e){console.error(e)}},[]); useEffect(()=>{try{localStorage.setItem(KEY,JSON.stringify(db))}catch(e){console.error(e)}},[db]);
 const go=m=>{setMode(m);setMsg("");setCode("")}; const leader=db.leaderships.find(x=>x.id===leaderId); const mine=db.activists.filter(x=>x.leaderId===leaderId); const leaders=useMemo(()=>db.leaderships.filter(x=>`${x.name} ${x.cpf} ${x.title}`.toLowerCase().includes(search.toLowerCase())),[db.leaderships,search]); const acts=useMemo(()=>db.activists.filter(x=>`${x.name} ${x.cpf} ${x.title}`.toLowerCase().includes(search.toLowerCase())),[db.activists,search]);
 const enter=admin=>{if(code!==CODE)return setMsg("Código inválido. Para o teste, use 328974.");setRole(admin?"admin":"leader");if(!admin&&!leaderId)setLeaderId(db.leaderships.at(-1)?.id||null);setView("dashboard");go(admin?"admin-area":"leader-area")};
 const release=admin=>{if(code!==CODE)return setMsg("Código inválido. Para o teste, use 328974.");setF(EMPTY);setReturnTo(admin?"admin-area":"leader-area");go(admin?"admin-reg":"leader-reg")};
 const saveLeader=e=>{e.preventDefault();if(!f.name.trim())return setMsg("Informe o nome completo.");if(!cpfOK(f.cpf))return setMsg("Informe um CPF válido.");if(!titleOK(f.title))return setMsg("O título deve conter exatamente 12 dígitos.");const x={...f,id:editing?.id||makeId(),created:editing?.created||Date.now(),updated:Date.now()};delete x._validation;setDb(d=>({...d,leaderships:editing?d.leaderships.map(a=>a.id===x.id?x:a):[...d.leaderships,x]}));setLeaderId(x.id);setEditing(null);setF(EMPTY);setRole(returnTo==="admin-area"?"admin":"leader");setView("dashboard");go(returnTo)};
 const saveAct=e=>{e.preventDefault();if(!leaderId)return setMsg("Nenhuma liderança selecionada.");if(!f.name.trim())return setMsg("Informe o nome completo.");if(!cpfOK(f.cpf))return setMsg("Informe um CPF válido.");if(!titleOK(f.title))return setMsg("O título deve conter exatamente 12 dígitos.");const x={...f,id:editing?.id||makeId(),leaderId,created:editing?.created||Date.now(),updated:Date.now()};delete x._validation;setDb(d=>({...d,activists:editing?d.activists.map(a=>a.id===x.id?x:a):[...d.activists,x]}));setEditing(null);setF(EMPTY);setView("activists");go(returnTo)};
 const startL=()=>{setF(EMPTY);setEditing(null);setReturnTo(role==="admin"?"admin-area":"home");go("leader-form")}; const startA=(lid=leaderId)=>{setLeaderId(lid||null);setF(EMPTY);setEditing(null);setReturnTo(role==="admin"?"admin-area":"leader-area");go("activist-form")}; const edit=(x,k)=>{setF({...EMPTY,...x});setEditing(x);setReturnTo(role==="admin"?"admin-area":"leader-area");go(k==="leader"?"leader-form":"activist-form")};
 const registerAdmin=e=>{e.preventDefault();const d=new FormData(e.currentTarget),name=String(d.get("name")||"").trim(),cpf=digits(d.get("cpf")),email=String(d.get("email")||"").trim();if(!name||!cpfOK(cpf))return setMsg("Informe nome e um CPF válido.");setDb(x=>({...x,admins:[...x.admins,{id:makeId(),name,cpf,email,created:Date.now()}]}));setRole("admin");setView("dashboard");go("admin-area")};
 const exportExcel=async()=>{try{const XLSX=await import("xlsx-js-style");const wb=XLSX.utils.book_new();const PINK="E59AB2",LIGHT="F8DCE7",PALE="FFF5F8",BORDER="E8C7D2",TEXT="49383F",WHITE="FFFFFF",LINK="A64F6D";const border={top:{style:"thin",color:{rgb:BORDER}},bottom:{style:"thin",color:{rgb:BORDER}},left:{style:"thin",color:{rgb:BORDER}},right:{style:"thin",color:{rgb:BORDER}}};const title={font:{name:"Aptos Display",sz:18,bold:true,color:{rgb:WHITE}},fill:{fgColor:{rgb:PINK}},alignment:{horizontal:"center",vertical:"center"},border};const subtitle={font:{name:"Aptos",sz:10,italic:true,color:{rgb:"8A707A"}},fill:{fgColor:{rgb:PALE}},alignment:{vertical:"center"},border};const section={font:{name:"Aptos",sz:12,bold:true,color:{rgb:TEXT}},fill:{fgColor:{rgb:LIGHT}},alignment:{vertical:"center"},border};const header={font:{name:"Aptos",sz:10,bold:true,color:{rgb:WHITE}},fill:{fgColor:{rgb:PINK}},alignment:{horizontal:"center",vertical:"center",wrapText:true},border};const cell={font:{name:"Aptos",sz:10,color:{rgb:TEXT}},alignment:{vertical:"center",wrapText:true},border};const link={...cell,font:{name:"Aptos",sz:10,bold:true,color:{rgb:LINK},underline:true}};const metric={font:{name:"Aptos",sz:20,bold:true,color:{rgb:PINK}},fill:{fgColor:{rgb:PALE}},alignment:{horizontal:"center",vertical:"center"},border};const metricLabel={font:{name:"Aptos",sz:10,bold:true,color:{rgb:TEXT}},fill:{fgColor:{rgb:LIGHT}},alignment:{horizontal:"center",vertical:"center"},border};const styleRange=(ws,range,style)=>{const r=XLSX.utils.decode_range(range);for(let y=r.s.r;y<=r.e.r;y++)for(let x=r.s.c;x<=r.e.c;x++){const a=XLSX.utils.encode_cell({r:y,c:x});if(!ws[a])ws[a]={t:"s",v:""};ws[a].s=style}};const nav=(ws,a,label,target)=>ws[a]={t:"s",v:label,s:link,l:{Target:`#'${target}'!A1`,Tooltip:`Ir para ${target}`}};const textCols=(ws,row,cols)=>cols.forEach(c=>{const a=XLSX.utils.encode_cell({r:row,c});if(ws[a]){ws[a].t="s";ws[a].v=String(ws[a].v??"")}});const add=(ws,name)=>XLSX.utils.book_append_sheet(wb,ws,name);
 const panelData=[["CADASTRO ELEITORAL • COORDENADORA DAINARA TORRES"],[`Exportado em ${new Date().toLocaleString("pt-BR")}`],[""],["RESUMO"],["Lideranças cadastradas",db.leaderships.length],["Ativistas cadastrados",db.activists.length],["Administradores cadastrados",db.admins.length],[""],["NAVEGAÇÃO"],["Lideranças"],["Ativistas"],["Administradores"],["Assessoria"]];const panel=XLSX.utils.aoa_to_sheet(panelData);panel["!cols"]=[{wch:34},{wch:24},{wch:24},{wch:24}];panel["A1"].s=title;panel["A2"].s=subtitle;styleRange(panel,"A4:B4",section);[5,6,7].forEach(r=>{panel[`A${r}`].s=metricLabel;panel[`B${r}`].s=metric});panel["A9"].s=section;nav(panel,"A10","Lideranças →","LIDERANÇAS");nav(panel,"A11","Ativistas →","ATIVISTAS");nav(panel,"A12","Administradores →","ADMINISTRADORES");nav(panel,"A13","Assessoria →","ASSESSORIA");panel["!merges"]=[{s:{r:0,c:0},e:{r:0,c:3}},{s:{r:1,c:0},e:{r:1,c:3}},{s:{r:3,c:0},e:{r:3,c:3}},{s:{r:8,c:0},e:{r:8,c:3}}];panel["!freeze"]={xSplit:0,ySplit:4};add(panel,"PAINEL");
 const lHeader=["Nome completo","Data de nascimento","CPF","Telefone","Endereço","Nome da mãe","E-mail","Bairro","CEP","Título de eleitor","Zona","Seção","Chave Pix","Titular Pix","Banco","Qtd. ativistas"];const lData=[["LIDERANÇAS"],["Cadastro completo das lideranças vinculadas à coordenação."],[],lHeader,...db.leaderships.map(l=>[l.name,dateBR(l.birth),cpfBR(l.cpf),phoneBR(l.phone),l.address,l.mother,l.email,l.neighborhood,cepBR(l.cep),l.title,l.zone,l.section,l.pix,l.pixname,l.bank,db.activists.filter(a=>a.leaderId===l.id).length])];const ls=XLSX.utils.aoa_to_sheet(lData);ls["!cols"]=[30,18,18,18,32,30,30,20,14,18,10,10,28,25,20,16].map(wch=>({wch}));ls["A1"].s=title;ls["A2"].s=subtitle;styleRange(ls,"A4:P4",header);for(let r=4;r<lData.length;r++){for(let c=0;c<16;c++){const a=XLSX.utils.encode_cell({r,c});if(ls[a])ls[a].s=c===0?link:cell}textCols(ls,r,[1,2,3,8,9,10,11]);const l=db.leaderships[r-4];if(l)ls[`A${r+1}`].l={Target:"#'ATIVISTAS'!A1",Tooltip:`Ver equipe de ${l.name}`}}ls["!freeze"]={xSplit:0,ySplit:4};ls["!autofilter"]={ref:`A4:P${Math.max(4,lData.length)}`};nav(ls,"A2","← Voltar ao painel","PAINEL");add(ls,"LIDERANÇAS");
 const aHeader=["Liderança","Nome completo","Data de nascimento","CPF","Telefone","Endereço","Nome da mãe","E-mail","Bairro","CEP","Título de eleitor","Zona","Seção","Chave Pix","Titular Pix","Banco"];const aData=[["ATIVISTAS POR LIDERANÇA"],["Equipes separadas visualmente para não misturar ativistas entre lideranças."],[],aHeader];[...db.leaderships].sort((a,b)=>String(a.name).localeCompare(String(b.name),"pt-BR")).forEach(l=>{aData.push([`LIDERANÇA: ${l.name}`]);const team=db.activists.filter(a=>a.leaderId===l.id).sort((a,b)=>String(a.name).localeCompare(String(b.name),"pt-BR"));if(team.length)team.forEach(a=>aData.push([l.name,a.name,dateBR(a.birth),cpfBR(a.cpf),phoneBR(a.phone),a.address,a.mother,a.email,a.neighborhood,cepBR(a.cep),a.title,a.zone,a.section,a.pix,a.pixname,a.bank]));else aData.push([l.name,"Nenhum ativista vinculado","","","","","","","","","","","","","",""])});const as=XLSX.utils.aoa_to_sheet(aData);as["!cols"]=[30,30,18,18,18,32,30,30,20,14,18,10,10,28,25,20].map(wch=>({wch}));as["A1"].s=title;as["A2"].s=subtitle;styleRange(as,"A4:P4",header);as["!merges"]=[{s:{r:0,c:0},e:{r:0,c:15}},{s:{r:1,c:0},e:{r:1,c:15}}];for(let r=4;r<aData.length;r++){const first=String(as[`A${r+1}`]?.v||"");if(first.startsWith("LIDERANÇA:")){styleRange(as,`A${r+1}:P${r+1}`,section);as["!merges"].push({s:{r,c:0},e:{r,c:15}})}else{for(let c=0;c<16;c++){const a=XLSX.utils.encode_cell({r,c});if(as[a])as[a].s=cell}textCols(as,r,[2,3,4,9,10,11,12])}}as["!freeze"]={xSplit:0,ySplit:4};as["!autofilter"]={ref:`A4:P${Math.max(4,aData.length)}`};nav(as,"A2","← Voltar ao painel","PAINEL");add(as,"ATIVISTAS");
 const adData=[["ADMINISTRADORES"],["Administradores autorizados no sistema."],[],["Nome completo","CPF","E-mail","Data do cadastro"],...db.admins.map(a=>[a.name,cpfBR(a.cpf),a.email,new Date(a.created).toLocaleString("pt-BR")])];const ad=XLSX.utils.aoa_to_sheet(adData);ad["!cols"]=[32,20,34,24].map(wch=>({wch}));ad["A1"].s=title;ad["A2"].s=subtitle;styleRange(ad,"A4:D4",header);for(let r=4;r<adData.length;r++){styleRange(ad,`A${r+1}:D${r+1}`,cell);textCols(ad,r,[1])}ad["!freeze"]={xSplit:0,ySplit:4};ad["!autofilter"]={ref:`A4:D${Math.max(4,adData.length)}`};nav(ad,"A2","← Voltar ao painel","PAINEL");add(ad,"ADMINISTRADORES");
 const scData=[["ASSESSORIA"],["Contatos disponibilizados pela coordenação."],[],["Nome","Telefone","E-mail"],...db.assessors.map(a=>[a.name,a.phone,a.email])];const sc=XLSX.utils.aoa_to_sheet(scData);sc["!cols"]=[34,34,36].map(wch=>({wch}));sc["A1"].s=title;sc["A2"].s=subtitle;styleRange(sc,"A4:C4",header);for(let r=4;r<scData.length;r++)styleRange(sc,`A${r+1}:C${r+1}`,cell);sc["!freeze"]={xSplit:0,ySplit:4};nav(sc,"A2","← Voltar ao painel","PAINEL");add(sc,"ASSESSORIA");
 XLSX.writeFile(wb,`cadastro-eleitoral-dainara-${new Date().toISOString().slice(0,10)}.xlsx`,{bookType:"xlsx",compression:true});setMsg("Excel exportado com painel, navegação, filtros e equipes separadas.")}catch(e){console.error(e);setMsg("Não foi possível gerar o Excel. Tente novamente.")}};
 const exportCSV=()=>{const h=["Liderança","Nome completo","Data de nascimento","CPF","Telefone","Endereço","Nome da mãe","E-mail","Bairro","CEP","Título de eleitor","Zona","Seção","Chave Pix","Titular Pix","Banco"];const rows=[];db.leaderships.forEach(l=>db.activists.filter(a=>a.leaderId===l.id).forEach(a=>rows.push([l.name,a.name,dateBR(a.birth),cpfBR(a.cpf),phoneBR(a.phone),a.address,a.mother,a.email,a.neighborhood,cepBR(a.cep),a.title,a.zone,a.section,a.pix,a.pixname,a.bank])));const csv=[h,...rows].map(r=>r.map(v=>`"${String(v??"").replace(/"/g,'""')}"`).join(";")).join("\r\n");const blob=new Blob(["\uFEFF"+csv],{type:"text/csv;charset=utf-8"});const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download=`cadastro-eleitoral-dainara-${new Date().toISOString().slice(0,10)}.csv`;a.click();URL.revokeObjectURL(url);setMsg("CSV exportado.")};
 if(mode==="home")return <main className="shell"><section className="hero"><b>Cadastro Eleitoral</b><h1>Coordenadora Dainara Torres</h1><p>Portal de acesso, cadastro e gestão de lideranças e ativistas.</p><div className="actions"><button onClick={()=>go("leader-access")}>Já sou liderança</button><button onClick={()=>go("leader-release")}>Se torne liderança</button><button className="outline" onClick={()=>go("admin-access")}>Acesso administrativo</button><button className="outline" onClick={()=>go("admin-release")}>Se tornar administrador</button></div><div className="home-note">Dados persistidos neste navegador durante a fase de teste.</div></section></main>;
 if(["leader-access","admin-access","leader-release","admin-release"].includes(mode)){const admin=mode.includes("admin"),rel=mode.includes("release");return <Access admin={admin} release={rel} code={code} setCode={setCode} msg={msg} onBack={()=>go("home")} onEnter={()=>rel?release(admin):enter(admin)} onSwitch={()=>go(rel?(admin?"admin-access":"leader-access"):(admin?"admin-release":"leader-release"))}/>}
 if(mode==="admin-reg")return <AdminReg back={()=>go("home")} save={registerAdmin} msg={msg}/>;if(mode==="leader-reg"||mode==="leader-form")return <Form kind="liderança" f={f} setF={setF} save={saveLeader} back={()=>go(mode==="leader-reg"?"home":returnTo)} msg={msg} edit={!!editing}/>;if(mode==="activist-form")return <Form kind="ativista" f={f} setF={setF} save={saveAct} back={()=>go(returnTo)} msg={msg} edit={!!editing}/>;
 if(!role)return <main className="shell"><section className="card"><h2>Acesso encerrado</h2><button className="primary" onClick={()=>go("home")}>Voltar ao início</button></section></main>;
 const admin=role==="admin",title=admin?"Painel administrativo":leader?`Olá, ${leader.name}`:"Área da liderança",logout=()=>{setRole(null);setLeaderId(null);setView("dashboard");go("home")};let content;
 if(view==="dashboard"){const recent=[...db.leaderships.map(x=>({...x,k:"Liderança"})),...db.activists.map(x=>({...x,k:"Ativista"}))].sort((a,b)=>(b.updated||b.created)-(a.updated||a.created)).slice(0,8);content=<><div className="cards"><div className="metric"><span className="label">Total de lideranças</span><div className="value">{admin?db.leaderships.length:leader?1:0}</div></div><div className="metric"><span className="label">Total de ativistas</span><div className="value">{admin?db.activists.length:mine.length}</div></div><div className="metric"><span className="label">Total de equipes</span><div className="value">{admin?db.leaderships.length:leader?1:0}</div></div><div className="metric"><span className="label">Cadastros recentes</span><div className="value">{recent.length}</div></div></div>{admin&&<div className="quick-grid"><button className="quick" onClick={()=>setView("leaderships")}>♙ <b>Gerenciar lideranças</b><span>Pesquisar e editar</span></button><button className="quick" onClick={()=>setView("activists")}>♧ <b>Gerenciar ativistas</b><span>Organizados por liderança</span></button><button className="quick" onClick={startL}>＋ <b>Nova liderança</b><span>Criar cadastro</span></button><button className="quick" onClick={exportExcel}>⇩ <b>Exportar Excel</b><span>Planilha rosa organizada</span></button></div>}{leader&&<div className="panel"><div className="page-head"><div><h3>Minha equipe</h3><p>{mine.length} ativista(s) vinculados.</p></div><button className="primary" onClick={()=>startA()}>＋ Adicionar ativista</button></div></div>}{!admin&&!leader&&<div className="panel empty"><b>Nenhuma liderança cadastrada neste navegador.</b><p>Cadastre sua liderança para começar.</p><button className="primary" onClick={startL}>Cadastrar minha liderança</button></div>}<div className="panel"><h3>Atividade recente</h3>{recent.length?recent.map(x=><div className="list-item" key={x.k+x.id}><div><b>{x.name}</b><small>{x.k} • {new Date(x.updated||x.created).toLocaleString("pt-BR")}</small></div>{x.k==="Ativista"&&<span>{db.leaderships.find(l=>l.id===x.leaderId)?.name||"Sem liderança"}</span>}</div>):<div className="empty">Nenhum cadastro realizado.</div>}</div></>}
 else if(view==="leaderships"&&admin)content=<div className="panel"><div className="page-head"><h2>Lideranças</h2><button className="primary" onClick={startL}>＋ Nova liderança</button></div><input className="search" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Pesquisar por nome, CPF ou título..."/>{leaders.length?leaders.map(l=><div className="list-item clickable" key={l.id} onClick={()=>{setDetail(l.id);setView("leadership-detail")}}><div><b>{l.name}</b><small>{cpfBR(l.cpf)} • Título {l.title}</small></div><span>{db.activists.filter(a=>a.leaderId===l.id).length} ativista(s) →</span></div>):<div className="empty">Nenhuma liderança encontrada.</div>}</div>;
 else if(view==="activists"){const list=admin?acts:mine.filter(a=>`${a.name} ${a.cpf} ${a.title}`.toLowerCase().includes(search.toLowerCase()));content=<div className="panel"><div className="page-head"><div><h2>{admin?"Ativistas":"Meus ativistas"}</h2><p>{admin?"A liderança aparece em cada linha para não misturar equipes.":`Liderança: ${leader?.name||"não cadastrada"}`}</p></div><button className="primary" onClick={()=>startA()}>＋ Adicionar ativista</button></div><input className="search" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Pesquisar por nome, CPF ou título..."/>{list.length?list.map(a=>{const l=db.leaderships.find(x=>x.id===a.leaderId);return <div className="list-item clickable" key={a.id} onClick={()=>{setDetail(a.id);setView("activist-detail")}}><div><b>{a.name}</b><small>{cpfBR(a.cpf)} • Título {a.title}</small></div><span className="leader-tag">👤 {l?.name||"Sem liderança"}</span></div>}):<div className="empty">Nenhum ativista encontrado.</div>}</div>}
 else if(view==="leadership-detail"&&admin){const l=db.leaderships.find(x=>x.id===detail),team=db.activists.filter(x=>x.leaderId===detail);content=<Detail title="Liderança" person={l} onBack={()=>setView("leaderships")} onEdit={()=>edit(l,"leader")} team={<div className="panel team-panel"><div className="page-head"><div><h3>Ativistas vinculados: {team.length}</h3><p>Equipe delimitada para facilitar a gestão.</p></div><button className="primary" onClick={()=>startA(l?.id)}>＋ Adicionar ativista</button></div>{team.length?team.map(a=><div className="list-item clickable" key={a.id} onClick={()=>{setDetail(a.id);setView("activist-detail")}}><div><b>{a.name}</b><small>{cpfBR(a.cpf)} • Título {a.title}</small></div><span>Ver cadastro →</span></div>):<div className="empty">Nenhum ativista vinculado.</div>}</div>}/>}
 else if(view==="activist-detail"){const a=db.activists.find(x=>x.id===detail),l=db.leaderships.find(x=>x.id===a?.leaderId);content=<Detail title="Cadastro do ativista" person={a} leader={l?.name} onBack={()=>setView("activists")} onEdit={()=>edit(a,"activist")}/>}
 else if(view==="profile"&&!admin)content=<Detail title="Meu cadastro" person={leader} onBack={()=>setView("dashboard")} onEdit={()=>leader&&edit(leader,"leader")}/>;
 else if(view==="assessors"&&!admin)content=<div className="panel"><h2>Contatos da assessoria</h2><p>Contatos disponibilizados pela coordenação.</p>{db.assessors.map(a=><div className="contact-card" key={a.id}><b>{a.name}</b><span>{a.phone}</span><span>{a.email}</span></div>)}</div>;
 else if(view==="admins"&&admin)content=<div className="panel"><div className="page-head"><h2>Administradores</h2><button className="primary" onClick={()=>go("admin-release")}>＋ Novo administrador</button></div>{db.admins.length?db.admins.map(a=><div className="list-item" key={a.id}><div><b>{a.name}</b><small>{cpfBR(a.cpf)} • {a.email||"Sem e-mail"}</small></div><span>{new Date(a.created).toLocaleDateString("pt-BR")}</span></div>):<div className="empty">Nenhum administrador cadastrado.</div>}</div>;
 else content=<div className="panel empty">Selecione uma opção no menu.</div>;
 return <div className="app-shell"><Side admin={admin} view={view} setView={v=>{setSearch("");setDetail(null);setView(v)}} logout={logout} newL={startL} newA={()=>startA()} exportExcel={exportExcel} exportCSV={exportCSV}/><div className="main"><header className="topbar"><div><h1>{title}</h1><p>{admin?"Visão geral dos cadastros e equipes.":leader?"Gerencie somente os ativistas vinculados à sua liderança.":"Cadastre sua liderança para começar."}</p></div>{admin&&<div style={{display:"flex",gap:10,flexWrap:"wrap"}}><button className="outline top-export" onClick={exportExcel}>⇩ Exportar Excel</button><button className="outline top-export" onClick={exportCSV}>⇩ Exportar CSV</button></div>}</header><main className="content">{msg&&<div className="result">{msg}</div>}{content}</main></div></div>;
}
