"use client";

import { useEffect, useMemo, useState } from "react";
import { MANAUS_ZONES } from "../data/territories";

const CODE = "328974";
const TSE = "https://www.tse.jus.br/servicos-eleitorais/autoatendimento-eleitoral";
const KEY = "cadastro-eleitoral-dainara-2026-v9";
const LEGACY_KEYS = ["cadastro-eleitoral-dainara-2026-v8"];
const EMPTY = {
  name: "", birth: "", cpf: "", phone: "", address: "", mother: "", email: "",
  neighborhood: "", cep: "", title: "", zone: "", section: "", pix: "", pixname: "", bank: ""
};
const EMPTY_ASSESSOR = { name: "", role: "", phone: "", email: "", notes: "" };
const digits = (v) => String(v || "").replace(/\D/g, "");
const makeId = () => globalThis.crypto?.randomUUID?.() || `${Date.now()}-${Math.random()}`;
const makePassword = () => String(Math.floor(10000000 + Math.random() * 90000000));

const cpfOK = (v) => {
  const c = digits(v);
  if (c.length !== 11 || /^(\d)\1+$/.test(c)) return false;
  let s = 0;
  for (let i = 0; i < 9; i++) s += +c[i] * (10 - i);
  let d = (s * 10) % 11;
  if (d === 10) d = 0;
  if (d !== +c[9]) return false;
  s = 0;
  for (let i = 0; i < 10; i++) s += +c[i] * (11 - i);
  d = (s * 10) % 11;
  if (d === 10) d = 0;
  return d === +c[10];
};

const titleOK = (v) => digits(v).length === 12;
const dateBR = (v) => (v ? String(v).split("-").reverse().join("/") : "");
const cpfBR = (v) => {
  const d = digits(v);
  return d.length === 11 ? d.replace(/(\d{3})(\d{3})(\d{3})(\d{2})/, "$1.$2.$3-$4") : String(v || "");
};
const cepBR = (v) => {
  const d = digits(v);
  return d.length === 8 ? d.replace(/(\d{5})(\d{3})/, "$1-$2") : String(v || "");
};
const phoneBR = (v) => {
  const d = digits(v);
  if (d.length === 11) return d.replace(/(\d{2})(\d{5})(\d{4})/, "($1) $2-$3");
  if (d.length === 10) return d.replace(/(\d{2})(\d{4})(\d{4})/, "($1) $2-$3");
  return String(v || "");
};

const fresh = () => ({ leaderships: [], activists: [], admins: [], assessors: [] });

function maskField(n, v) {
  const d = digits(v);
  if (n === "cpf") return cpfBR(d);
  if (n === "phone") return phoneBR(d);
  if (n === "cep") return cepBR(d);
  if (n === "title") return d.slice(0, 12);
  if (n === "zone" || n === "section") return d;
  return String(v || "");
}

function Field({ f, setF, n, label, type = "text", required = false, placeholder }) {
  const numeric = ["cpf", "phone", "cep", "title", "zone", "section"].includes(n);
  const max = { cpf: 14, phone: 15, cep: 9, title: 12, zone: 5, section: 5 }[n];
  return <label className="field"><span>{label}{required ? " *" : ""}</span><input type={type} required={required} value={numeric ? maskField(n, f[n]) : (f[n] || "")} placeholder={placeholder} maxLength={max} inputMode={numeric ? "numeric" : undefined} onChange={(e) => { let v = e.target.value; if (numeric) { const limits = { cpf: 11, phone: 11, cep: 8, title: 12, zone: 5, section: 5 }; v = digits(v).slice(0, limits[n]); } setF((x) => ({ ...x, [n]: v })); }} /></label>;
}

function Form({ kind, f, setF, save, back, msg, edit, admin, leaderships, leaderId, setLeaderId }) {
  return <main className="shell"><section className="card wide"><button className="back" onClick={back}>← Voltar</button><h2>{edit ? `Editar ${kind}` : `Cadastro de ${kind}`}</h2><p>Preencha os dados e salve o cadastro.</p><form onSubmit={save}>
    <h3>Dados pessoais</h3><div className="form-grid"><Field f={f} setF={setF} n="name" label="Nome completo" required/><Field f={f} setF={setF} n="birth" label="Data de nascimento" type="date"/><Field f={f} setF={setF} n="cpf" label="CPF" required placeholder="000.000.000-00"/><Field f={f} setF={setF} n="phone" label="Celular / telefone" placeholder="(00) 00000-0000"/><Field f={f} setF={setF} n="address" label="Endereço"/><Field f={f} setF={setF} n="mother" label="Nome da mãe"/><Field f={f} setF={setF} n="email" label="E-mail" type="email"/><Field f={f} setF={setF} n="neighborhood" label="Bairro"/><Field f={f} setF={setF} n="cep" label="CEP" placeholder="00000-000"/></div>
    {kind === "ativista" && admin && <><h3>Vínculo</h3><div className="form-grid"><label className="field"><span>Liderança responsável *</span><select required value={leaderId || ""} onChange={(e) => setLeaderId(e.target.value)}><option value="">Selecione a liderança</option>{leaderships.map((l) => <option key={l.id} value={l.id}>{l.name} — CPF {cpfBR(l.cpf)}</option>)}</select></label></div></>}
    <h3>Dados eleitorais</h3><div className="form-grid three"><Field f={f} setF={setF} n="title" label="Título de eleitor" required placeholder="000000000000"/><Field f={f} setF={setF} n="zone" label="Zona"/><Field f={f} setF={setF} n="section" label="Seção"/></div>
    <div className="validation-row"><button type="button" className="outline" onClick={() => setF((x) => ({ ...x, _validation: `${cpfOK(x.cpf) ? "✓ CPF válido" : "✗ CPF inválido"} • ${titleOK(x.title) ? "✓ Título válido" : "✗ Título inválido"}` }))}>Validar CPF e título</button><a className="tse" href={TSE} target="_blank" rel="noreferrer">Consultar situação no TSE ↗</a></div>
    <h3>Dados de pagamento</h3><div className="form-grid three"><Field f={f} setF={setF} n="pix" label="Chave Pix"/><Field f={f} setF={setF} n="pixname" label="Nome do titular"/><Field f={f} setF={setF} n="bank" label="Banco"/></div>
    {f._validation && <div className="result">{f._validation}</div>}{msg && <div className="result">{msg}</div>}<button className="primary submit">{edit ? "Salvar alterações" : `Cadastrar ${kind}`}</button>
  </form></section></main>;
}

function Access({ admin, release, cpf, setCpf, password, setPassword, code, setCode, msg, onEnter, onBack, onSwitch }) {
  return <main className="shell"><section className="card auth-card"><button className="back" onClick={onBack}>← Voltar</button><h2>{release ? (admin ? "Se tornar administrador" : "Se torne liderança") : (admin ? "Acesso administrativo" : "Já sou liderança")}</h2>
    <p>{release ? "Informe o código de liberação para continuar." : admin ? "Acesse usando o CPF do administrador cadastrado." : "Acesse usando o CPF da liderança e a senha gerada no cadastro."}</p>
    {release ? <label className="field"><span>Código de liberação</span><input autoFocus inputMode="numeric" maxLength={6} value={code} placeholder="000000" onChange={(e) => setCode(digits(e.target.value).slice(0, 6))} onKeyDown={(e) => e.key === "Enter" && onEnter()}/></label> : <>
      <label className="field"><span>CPF</span><input autoFocus inputMode="numeric" maxLength={14} value={cpfBR(cpf)} placeholder="000.000.000-00" onChange={(e) => setCpf(digits(e.target.value).slice(0, 11))} onKeyDown={(e) => e.key === "Enter" && onEnter()}/></label>
      {admin ? <div className="login-hint"><span>Credencial</span><b>CPF do administrador cadastrado</b></div> : <label className="field"><span>Senha</span><input type="password" inputMode="numeric" maxLength={8} value={password} placeholder="Senha de 8 dígitos" onChange={(e) => setPassword(e.target.value.replace(/\D/g, "").slice(0, 8))} onKeyDown={(e) => e.key === "Enter" && onEnter()}/></label>}
    </>}
    {msg && <div className="result">{msg}</div>}<button className="primary" onClick={onEnter}>{release ? "Continuar" : "Entrar"}</button>{release && <div className="auth-note">Código de teste: <b>328974</b></div>}<button className="link-button" onClick={onSwitch}>{release ? (admin ? "Voltar ao acesso administrativo" : "Já sou liderança") : (admin ? "Se tornar administrador" : "Se torne liderança")}</button>
  </section></main>;
}

function AdminReg({ back, save, msg }) {
  return <main className="shell"><section className="card auth-card"><button className="back" onClick={back}>← Voltar</button><h2>Cadastro de administrador</h2><p>O acesso foi liberado pelo código 328974. Depois do cadastro, a entrada será feita somente com o CPF cadastrado.</p><form onSubmit={save}><label className="field"><span>Nome completo *</span><input name="name" required/></label><label className="field"><span>CPF *</span><input name="cpf" required maxLength={14} inputMode="numeric" placeholder="000.000.000-00" onChange={(e) => { e.currentTarget.value = cpfBR(e.currentTarget.value); }}/></label><label className="field"><span>E-mail</span><input name="email" type="email"/></label>{msg && <div className="result">{msg}</div>}<button className="primary">Concluir cadastro</button></form></section></main>;
}

function Credential({ person, password, onAccess, onBack }) {
  if (!person) return <main className="shell"><section className="card auth-card"><h2>Cadastro concluído</h2><p>O cadastro foi salvo, mas a tela de credenciais precisa ser recuperada.</p><button className="primary" onClick={onBack}>Voltar ao início</button></section></main>;
  const shownPassword = password || person.password || "";
  const copy = async () => { try { await navigator.clipboard.writeText(shownPassword); } catch {} };
  return <main className="shell"><section className="card auth-card credential-card"><div className="credential-success">✓ CADASTRO CONCLUÍDO</div><h2>Senha da liderança gerada</h2><p>{person.name}, guarde esta credencial. Ela será usada com seu CPF para entrar na Área da Liderança.</p><div className="credential-box featured"><div className="credential-item"><span>CPF</span><b>{cpfBR(person.cpf)}</b></div><div className="credential-divider"/><div className="credential-item"><span>SENHA DE ACESSO</span><strong>{shownPassword}</strong></div><button className="copy-password" onClick={copy}>Copiar senha</button></div><div className="credential-warning"><b>Importante:</b> esta senha é necessária para acessar a Área da Liderança. Anote ou copie antes de continuar.</div><button className="primary" onClick={onAccess}>Ir para acesso da liderança</button><button className="link-button" onClick={onBack}>Voltar ao início</button></section></main>;
}

function AssessorForm({ form, setForm, save, cancel, editing }) {
  return <div className="assessor-editor"><div className="editor-title"><div><h3>{editing ? "Editar contato" : "Novo contato da assessoria"}</h3><p>Este contato ficará disponível automaticamente para todas as lideranças.</p></div><button className="back small-back" onClick={cancel}>Cancelar</button></div><form onSubmit={save}><div className="form-grid"><label className="field"><span>Nome do contato *</span><input required value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })}/></label><label className="field"><span>Função / descrição</span><input value={form.role} onChange={(e) => setForm({ ...form, role: e.target.value })} placeholder="Ex.: Assessoria, coordenação, jurídico..."/></label><label className="field"><span>Telefone</span><input value={form.phone} onChange={(e) => setForm({ ...form, phone: phoneBR(e.target.value) })} placeholder="(00) 00000-0000"/></label><label className="field"><span>E-mail</span><input type="email" value={form.email} onChange={(e) => setForm({ ...form, email: e.target.value })}/></label></div><label className="field"><span>Observações</span><textarea value={form.notes} onChange={(e) => setForm({ ...form, notes: e.target.value })} rows={3} placeholder="Informações adicionais para as lideranças..."/></label><button className="primary">{editing ? "Salvar alterações" : "Adicionar contato"}</button></form></div>;
}

function AdminLeadershipCredential({ person, onReset }) {
  const [newPassword, setNewPassword] = useState("");
  const copy = async () => { try { await navigator.clipboard.writeText(newPassword); } catch {} };
  const reset = () => {
    if (!window.confirm("Gerar uma nova senha? A senha anterior deixará de funcionar.")) return;
    setNewPassword(onReset());
  };
  return <div className="panel credential-admin"><h3>Credencial de acesso</h3><p>Por segurança, a senha atual não pode ser exibida. Gere uma nova senha para repassar à liderança.</p><button type="button" className="outline" onClick={reset}>Gerar nova senha</button>{newPassword && <div className="credential-box"><div className="credential-item"><span>NOVA SENHA DE ACESSO</span><strong>{newPassword}</strong></div><p>Copie e entregue esta senha agora. A senha anterior foi invalidada.</p><button type="button" className="copy-password" onClick={copy}>Copiar nova senha</button></div>}</div>;
}

function Detail({ person, title, leader, onBack, onEdit, team, credential }) {
  if (!person) return <main className="shell"><section className="card"><button className="back" onClick={onBack}>← Voltar</button><div className="empty">Cadastro não encontrado.</div></section></main>;
  return <main className="shell"><section className="card wide"><div className="page-head"><div><button className="back" onClick={onBack}>← Voltar</button><h2>{title}</h2></div><button className="primary" onClick={onEdit}>Editar cadastro</button></div>{leader && <div className="context-badge">Liderança: <b>{leader}</b></div>}<div className="detail-grid"><div className="panel"><h3>Dados pessoais</h3><p><b>Nome:</b> {person.name}</p><p><b>Nascimento:</b> {dateBR(person.birth) || "—"}</p><p><b>CPF:</b> {cpfBR(person.cpf) || "—"}</p><p><b>Telefone:</b> {phoneBR(person.phone) || "—"}</p><p><b>E-mail:</b> {person.email || "—"}</p><p><b>Nome da mãe:</b> {person.mother || "—"}</p><p><b>Endereço:</b> {person.address || "—"}</p><p><b>Bairro:</b> {person.neighborhood || "—"}</p><p><b>CEP:</b> {cepBR(person.cep) || "—"}</p></div><div className="panel"><h3>Dados eleitorais</h3><p><b>Título:</b> {person.title || "—"}</p><p><b>Zona:</b> {person.zone || "—"}</p><p><b>Seção:</b> {person.section || "—"}</p><h3>Dados de pagamento</h3><p><b>Pix:</b> {person.pix || "—"}</p><p><b>Titular:</b> {person.pixname || "—"}</p><p><b>Banco:</b> {person.bank || "—"}</p></div></div>{credential}{team}</section></main>;
}


const MANAUS_MAP_ZONES = [
  { name: "Norte", path: "M164 12 L238 8 L252 103 L218 147 L154 135 L138 75 Z", label: [193,76] },
  { name: "Leste", path: "M252 103 L439 92 L450 174 L405 236 L284 232 L240 182 Z", label: [343,163] },
  { name: "Sul", path: "M168 217 L250 207 L285 244 L266 292 L198 303 L153 268 Z", label: [219,255] },
  { name: "Centro-Sul", path: "M197 171 L266 157 L285 204 L250 224 L205 213 Z", label: [240,192] },
  { name: "Centro-Oeste", path: "M122 142 L197 132 L212 175 L177 204 L126 186 Z", label: [163,166] },
  { name: "Oeste", path: "M28 77 L122 60 L154 135 L126 186 L153 268 L82 242 L43 172 Z", label: [91,159] }
];

function ManausCoverageMap({ db }) {
  const [hovered, setHovered] = useState(null);
  const allPeople = [...(db.leaderships || []), ...(db.activists || []), ...(db.families || [])];
  const counts = Object.fromEntries(MANAUS_MAP_ZONES.map(({ name }) => [name, allPeople.filter((person) => MANAUS_ZONES[person.neighborhood] === name).length]));
  const color = (count) => count === 0 ? "#fff" : count <= 10 ? "#fde1eb" : count <= 50 ? "#ee9ab5" : "#c54672";
  const active = MANAUS_MAP_ZONES.find((zone) => zone.name === hovered);
  return <section className="panel"><div className="page-head"><div><h2>Mapa de cadastros por zona</h2><p>Manaus — bairros oficiais por zona administrativa.</p></div></div><div style={{position:"relative",maxWidth:760,margin:"12px auto 0"}}><svg viewBox="0 0 470 315" role="img" aria-label="Mapa interativo das zonas de Manaus" style={{width:"100%",display:"block",filter:"drop-shadow(0 8px 14px rgba(157,91,116,.10))",background:"#fff",borderRadius:16}}>{MANAUS_MAP_ZONES.map((zone) => <g key={zone.name} onMouseEnter={() => setHovered(zone.name)} onMouseLeave={() => setHovered(null)} style={{cursor:"default"}}><path d={zone.path} fill={color(counts[zone.name])} stroke={hovered === zone.name ? "#9f4d69" : "#8d6573"} strokeWidth={hovered === zone.name ? 4 : 1.4} style={{transition:"fill .18s, stroke .18s"}}/><text x={zone.label[0]} y={zone.label[1]} textAnchor="middle" fontSize="13" fontWeight="800" fill="#49383f">{zone.name}</text></g>)}</svg>{active && <div role="status" style={{position:"absolute",left:"50%",bottom:12,transform:"translateX(-50%)",background:"#49383f",color:"#fff",padding:"10px 14px",borderRadius:10,fontWeight:800,boxShadow:"0 8px 20px rgba(0,0,0,.16)",whiteSpace:"nowrap"}}>{active.name}: {counts[active.name]} cadastro(s)</div>}</div><div style={{display:"flex",gap:12,flexWrap:"wrap",marginTop:16,fontSize:13,color:"#6d5961"}}><span><i style={{display:"inline-block",width:12,height:12,borderRadius:3,background:"#fff",border:"1px solid #d9bcc7",marginRight:5}}/>0</span><span><i style={{display:"inline-block",width:12,height:12,borderRadius:3,background:"#fde1eb",marginRight:5}}/>1–10</span><span><i style={{display:"inline-block",width:12,height:12,borderRadius:3,background:"#ee9ab5",marginRight:5}}/>11–50</span><span><i style={{display:"inline-block",width:12,height:12,borderRadius:3,background:"#c54672",marginRight:5}}/>51–100</span></div></section>;
}

function Side({ admin, view, setView, logout, newL, newA, exportExcel, exportCSV }) {
  return <aside className="sidebar"><div className="brand"><b>Cadastro Eleitoral</b><span>{admin ? "Coordenadora Dainara Torres" : "Área da liderança"}</span></div><div className="nav-title">Menu</div><nav><button className={view === "dashboard" ? "active" : ""} onClick={() => setView("dashboard")}>⌂ Dashboard</button>{admin ? <><button className={view === "leaderships" ? "active" : ""} onClick={() => setView("leaderships")}>♙ Lideranças</button><button className={view === "activists" ? "active" : ""} onClick={() => setView("activists")}>♧ Ativistas</button><button className={view === "admins" ? "active" : ""} onClick={() => setView("admins")}>◉ Administradores</button><button className={view === "assessors" ? "active" : ""} onClick={() => setView("assessors")}>☎ Assessoria</button><button onClick={newL}>＋ Nova liderança</button></> : <><button className={view === "activists" ? "active" : ""} onClick={() => setView("activists")}>♧ Meus ativistas</button><button onClick={newA}>＋ Adicionar ativista</button><button className={view === "profile" ? "active" : ""} onClick={() => setView("profile")}>👤 Meu cadastro</button><button className={view === "assessors" ? "active" : ""} onClick={() => setView("assessors")}>☎ Contatos da assessoria</button></>}</nav>{admin && <><button className="export-side" onClick={exportExcel}>⇩ Exportar Excel</button><button className="export-side" onClick={exportCSV}>⇩ Exportar CSV</button></>}<button className="logout" onClick={logout}>Sair</button></aside>;
}

export default function Portal() {
  const [mode, setMode] = useState("home"), [code, setCode] = useState(""), [cpf, setCpf] = useState(""), [password, setPassword] = useState(""), [msg, setMsg] = useState(""), [f, setF] = useState(EMPTY), [db, setDb] = useState(fresh()), [role, setRole] = useState(null), [leaderId, setLeaderId] = useState(null), [view, setView] = useState("dashboard"), [search, setSearch] = useState(""), [detail, setDetail] = useState(null), [editing, setEditing] = useState(null), [returnTo, setReturnTo] = useState("home"), [generatedPassword, setGeneratedPassword] = useState(""), [generatedPerson, setGeneratedPerson] = useState(null), [assessorForm, setAssessorForm] = useState(EMPTY_ASSESSOR), [editingAssessor, setEditingAssessor] = useState(null), [assessorEditorOpen, setAssessorEditorOpen] = useState(false);

  useEffect(() => { try { const raw = localStorage.getItem(KEY) || LEGACY_KEYS.map((k) => localStorage.getItem(k)).find(Boolean); if (raw) { const parsed = JSON.parse(raw); setDb({ ...fresh(), ...parsed, assessors: Array.isArray(parsed.assessors) ? parsed.assessors : [] }); } } catch (e) { console.error(e); } }, []);
  useEffect(() => { try { localStorage.setItem(KEY, JSON.stringify(db)); } catch (e) { console.error(e); } }, [db]);
  useEffect(() => { try { if (mode === "leader-credentials" && !generatedPerson) { const raw = sessionStorage.getItem(`${KEY}-new-leadership`); if (raw) { const saved = JSON.parse(raw); setGeneratedPerson(saved.person || null); setGeneratedPassword(String(saved.password || saved.person?.password || "")); } } } catch (e) { console.error(e); } }, [mode, generatedPerson]);

  const go = (next) => { setMode(next); setMsg(""); };
  const logout = () => { setRole(null); setLeaderId(null); setCpf(""); setPassword(""); setCode(""); setSearch(""); setDetail(null); setView("dashboard"); go("home"); };
  const leader = db.leaderships.find((x) => x.id === leaderId), mine = db.activists.filter((x) => x.leaderId === leaderId);
  const leaders = useMemo(() => db.leaderships.filter((x) => `${x.name} ${x.cpf} ${x.title}`.toLowerCase().includes(search.toLowerCase())), [db.leaderships, search]);
  const acts = useMemo(() => db.activists.filter((x) => `${x.name} ${x.cpf} ${x.title}`.toLowerCase().includes(search.toLowerCase())), [db.activists, search]);

  const enterAdmin = () => { if (!cpfOK(cpf)) return setMsg("Informe um CPF válido."); const a = db.admins.find((x) => digits(x.cpf) === digits(cpf)); if (!a) return setMsg("CPF não cadastrado como administrador."); setRole("admin"); setLeaderId(null); setView("dashboard"); go("admin-area"); };
  const enterLeader = () => { if (!cpfOK(cpf)) return setMsg("Informe um CPF válido."); if (!password || password.length !== 8) return setMsg("Informe a senha de 8 dígitos gerada no cadastro."); const l = db.leaderships.find((x) => digits(x.cpf) === digits(cpf)); if (!l) return setMsg("CPF não cadastrado como liderança."); if (!l.password) return setMsg("Esta liderança ainda não possui senha."); if (String(l.password) !== String(password)) return setMsg("CPF ou senha incorretos."); setRole("leader"); setLeaderId(l.id); setView("dashboard"); go("leader-area"); };
  const release = (admin) => { if (code !== CODE) return setMsg("Código inválido. Para o teste, use 328974."); setF(EMPTY); setEditing(null); setReturnTo(admin ? "admin-area" : "home"); go(admin ? "admin-reg" : "leader-reg"); };

  const saveLeader = (e) => { e.preventDefault(); if (!f.name.trim()) return setMsg("Informe o nome completo."); if (!cpfOK(f.cpf)) return setMsg("Informe um CPF válido."); if (!titleOK(f.title)) return setMsg("O título deve conter exatamente 12 dígitos."); const duplicate = db.leaderships.find((x) => digits(x.cpf) === digits(f.cpf) && x.id !== editing?.id); if (duplicate) return setMsg("Já existe uma liderança cadastrada com este CPF."); const isEditing = Boolean(editing), generated = editing?.password || makePassword(), x = { ...f, id: editing?.id || makeId(), password: generated, created: editing?.created || Date.now(), updated: Date.now() }; delete x._validation; setDb((d) => ({ ...d, leaderships: isEditing ? d.leaderships.map((a) => a.id === x.id ? x : a) : [...d.leaderships, x] })); setLeaderId(x.id); setEditing(null); setF(EMPTY); if (!isEditing) { try { sessionStorage.setItem(`${KEY}-new-leadership`, JSON.stringify({ person: x, password: generated })); } catch (err) { console.error(err); } setGeneratedPassword(generated); setGeneratedPerson(x); go("leader-credentials"); } else { setRole(returnTo === "admin-area" ? "admin" : "leader"); setView("dashboard"); go(returnTo); } };
  const saveAct = (e) => { e.preventDefault(); if (!leaderId) return setMsg("Selecione uma liderança para vincular o ativista."); if (!f.name.trim()) return setMsg("Informe o nome completo."); if (!cpfOK(f.cpf)) return setMsg("Informe um CPF válido."); if (!titleOK(f.title)) return setMsg("O título deve conter exatamente 12 dígitos."); const duplicate = db.activists.find((x) => digits(x.cpf) === digits(f.cpf) && x.id !== editing?.id); if (duplicate) return setMsg("Já existe um ativista cadastrado com este CPF."); const x = { ...f, id: editing?.id || makeId(), leaderId, created: editing?.created || Date.now(), updated: Date.now() }; delete x._validation; setDb((d) => ({ ...d, activists: editing ? d.activists.map((a) => a.id === x.id ? x : a) : [...d.activists, x] })); setEditing(null); setF(EMPTY); setView("activists"); go(returnTo); };
  const startL = () => { setF(EMPTY); setEditing(null); setReturnTo(role === "admin" ? "admin-area" : "home"); go("leader-form"); };
  const startA = (lid = leaderId) => { setLeaderId(lid || null); setF(EMPTY); setEditing(null); setReturnTo(role === "admin" ? "admin-area" : "leader-area"); go("activist-form"); };
  const edit = (x, k) => { setF({ ...EMPTY, ...x }); setEditing(x); setLeaderId(x.leaderId || leaderId); setReturnTo(role === "admin" ? "admin-area" : "leader-area"); go(k === "leader" ? "leader-form" : "activist-form"); };

  const startAssessor = () => { setEditingAssessor(null); setAssessorForm({ ...EMPTY_ASSESSOR }); setMsg(""); setAssessorEditorOpen(true); setView("assessors"); };
  const editAssessor = (a) => { setEditingAssessor(a); setAssessorForm({ ...EMPTY_ASSESSOR, ...a }); setAssessorEditorOpen(true); setMsg(""); };
  const cancelAssessor = () => { setEditingAssessor(null); setAssessorForm(EMPTY_ASSESSOR); setAssessorEditorOpen(false); };
  const saveAssessor = (e) => { e.preventDefault(); if (!assessorForm.name.trim()) return setMsg("Informe o nome do contato da assessoria."); const item = { ...assessorForm, id: editingAssessor?.id || makeId(), created: editingAssessor?.created || Date.now(), updated: Date.now() }; setDb((d) => ({ ...d, assessors: editingAssessor ? d.assessors.map((a) => a.id === item.id ? item : a) : [...d.assessors, item] })); setMsg(editingAssessor ? "Contato da assessoria atualizado." : "Contato da assessoria adicionado."); cancelAssessor(); };
  const removeAssessor = (id) => { if (!window.confirm("Excluir este contato da assessoria? Ele deixará de aparecer para as lideranças.")) return; setDb((d) => ({ ...d, assessors: d.assessors.filter((a) => a.id !== id) })); setMsg("Contato removido."); };
  const saveAdmin = (e) => { e.preventDefault(); const fd = new FormData(e.currentTarget), name = String(fd.get("name") || "").trim(), adminCpf = digits(fd.get("cpf")), email = String(fd.get("email") || "").trim(); if (!name) return setMsg("Informe o nome completo."); if (!cpfOK(adminCpf)) return setMsg("Informe um CPF válido."); if (db.admins.some((x) => digits(x.cpf) === adminCpf)) return setMsg("Já existe um administrador cadastrado com este CPF."); const admin = { id: makeId(), name, cpf: adminCpf, email, created: Date.now() }; setDb((d) => ({ ...d, admins: [...d.admins, admin] })); setRole("admin"); setLeaderId(null); setView("dashboard"); go("admin-area"); };

  const exportExcel = async () => {
    try {
      const XLSX = await import("xlsx-js-style"), wb = XLSX.utils.book_new();
      const PINK="E59AB2",LIGHT="F8DCE7",PALE="FFF5F8",BORDER="E8C7D2",TEXT="49383F",WHITE="FFFFFF",LINK="A64F6D";
      const border={top:{style:"thin",color:{rgb:BORDER}},bottom:{style:"thin",color:{rgb:BORDER}},left:{style:"thin",color:{rgb:BORDER}},right:{style:"thin",color:{rgb:BORDER}}};
      const title={font:{name:"Aptos Display",sz:18,bold:true,color:{rgb:WHITE}},fill:{fgColor:{rgb:PINK}},alignment:{horizontal:"center",vertical:"center"},border};
      const subtitle={font:{name:"Aptos",sz:10,italic:true,color:{rgb:"8A707A"}},fill:{fgColor:{rgb:PALE}},alignment:{vertical:"center"},border};
      const section={font:{name:"Aptos",sz:12,bold:true,color:{rgb:TEXT}},fill:{fgColor:{rgb:LIGHT}},alignment:{vertical:"center"},border};
      const header={font:{name:"Aptos",sz:10,bold:true,color:{rgb:WHITE}},fill:{fgColor:{rgb:PINK}},alignment:{horizontal:"center",vertical:"center",wrapText:true},border};
      const cell={font:{name:"Aptos",sz:10,color:{rgb:TEXT}},alignment:{vertical:"center",wrapText:true},border};
      const link={...cell,font:{name:"Aptos",sz:10,bold:true,color:{rgb:LINK},underline:true}};
      const metric={font:{name:"Aptos",sz:20,bold:true,color:{rgb:PINK}},fill:{fgColor:{rgb:PALE}},alignment:{horizontal:"center",vertical:"center"},border};
      const metricLabel={font:{name:"Aptos",sz:10,bold:true,color:{rgb:TEXT}},fill:{fgColor:{rgb:LIGHT}},alignment:{horizontal:"center",vertical:"center"},border};
      const styleRange=(ws,range,style)=>{const r=XLSX.utils.decode_range(range);for(let y=r.s.r;y<=r.e.r;y++)for(let x=r.s.c;x<=r.e.c;x++){const a=XLSX.utils.encode_cell({r:y,c:x});if(!ws[a])ws[a]={t:"s",v:""};ws[a].s=style;}};
      const nav=(ws,a,label,target)=>ws[a]={t:"s",v:label,s:link,l:{Target:`#'${target}'!A1`,Tooltip:`Ir para ${target}`}};
      const textCols=(ws,row,cols)=>cols.forEach(c=>{const a=XLSX.utils.encode_cell({r:row,c});if(ws[a]){ws[a].t="s";ws[a].v=String(ws[a].v??"");}});
      const add=(ws,name)=>XLSX.utils.book_append_sheet(wb,ws,name);
      const panel=XLSX.utils.aoa_to_sheet([["CADASTRO ELEITORAL • COORDENADORA DAINARA TORRES"],[`Exportado em ${new Date().toLocaleString("pt-BR")}`],[""],["RESUMO"],["Lideranças cadastradas",db.leaderships.length],["Ativistas cadastrados",db.activists.length],["Administradores cadastrados",db.admins.length],["Contatos da assessoria",db.assessors.length],[""],["NAVEGAÇÃO"],["Lideranças"],["Ativistas"],["Administradores"],["Assessoria"]]);
      panel["!cols"]=[{wch:34},{wch:24},{wch:24},{wch:24}];panel["A1"].s=title;panel["A2"].s=subtitle;styleRange(panel,"A4:B4",section);[5,6,7,8].forEach(r=>{panel[`A${r}`].s=metricLabel;panel[`B${r}`].s=metric;});panel["A10"].s=section;nav(panel,"A11","Lideranças →","LIDERANÇAS");nav(panel,"A12","Ativistas →","ATIVISTAS");nav(panel,"A13","Administradores →","ADMINISTRADORES");nav(panel,"A14","Assessoria →","ASSESSORIA");panel["!merges"]=[{s:{r:0,c:0},e:{r:0,c:3}},{s:{r:1,c:0},e:{r:1,c:3}},{s:{r:3,c:0},e:{r:3,c:3}},{s:{r:9,c:0},e:{r:9,c:3}}];panel["!freeze"]={xSplit:0,ySplit:4};add(panel,"PAINEL");
      const lHeader=["Nome completo","Data de nascimento","CPF","Telefone","Endereço","Nome da mãe","E-mail","Bairro","CEP","Título de eleitor","Zona","Seção","Chave Pix","Titular Pix","Banco","Qtd. ativistas"];const lData=[["LIDERANÇAS"],["Cadastro completo das lideranças vinculadas à coordenação."],[""],lHeader,...db.leaderships.map(l=>[l.name,dateBR(l.birth),cpfBR(l.cpf),phoneBR(l.phone),l.address,l.mother,l.email,l.neighborhood,cepBR(l.cep),l.title,l.zone,l.section,l.pix,l.pixname,l.bank,db.activists.filter(a=>a.leaderId===l.id).length])];const ls=XLSX.utils.aoa_to_sheet(lData);ls["!cols"]=[30,18,18,18,32,30,30,20,14,18,10,10,28,25,20,16].map(wch=>({wch}));ls["A1"].s=title;ls["A2"].s=subtitle;styleRange(ls,"A4:P4",header);for(let r=4;r<lData.length;r++){for(let c=0;c<16;c++){const a=XLSX.utils.encode_cell({r,c});if(ls[a])ls[a].s=c===0?link:cell;}textCols(ls,r,[1,2,3,8,9,10,11]);}ls["!freeze"]={xSplit:0,ySplit:4};ls["!autofilter"]={ref:`A4:P${Math.max(4,lData.length)}`};nav(ls,"A2","← Voltar ao painel","PAINEL");add(ls,"LIDERANÇAS");
      const aHeader=["Liderança","Nome completo","Data de nascimento","CPF","Telefone","Endereço","Nome da mãe","E-mail","Bairro","CEP","Título de eleitor","Zona","Seção","Chave Pix","Titular Pix","Banco"];const aData=[["ATIVISTAS POR LIDERANÇA"],["Equipes separadas visualmente para não misturar ativistas entre lideranças."],[""],aHeader];[...db.leaderships].sort((a,b)=>String(a.name).localeCompare(String(b.name),"pt-BR")).forEach(l=>{aData.push([`LIDERANÇA: ${l.name}`]);const team=db.activists.filter(a=>a.leaderId===l.id).sort((a,b)=>String(a.name).localeCompare(String(b.name),"pt-BR"));if(team.length)team.forEach(a=>aData.push([l.name,a.name,dateBR(a.birth),cpfBR(a.cpf),phoneBR(a.phone),a.address,a.mother,a.email,a.neighborhood,cepBR(a.cep),a.title,a.zone,a.section,a.pix,a.pixname,a.bank]));else aData.push([l.name,"Nenhum ativista vinculado"]);});const as=XLSX.utils.aoa_to_sheet(aData);as["!cols"]=[30,30,18,18,18,32,30,30,20,14,18,10,10,28,25,20].map(wch=>({wch}));as["A1"].s=title;as["A2"].s=subtitle;styleRange(as,"A4:P4",header);as["!merges"]=[{s:{r:0,c:0},e:{r:0,c:15}},{s:{r:1,c:0},e:{r:1,c:15}}];for(let r=4;r<aData.length;r++){const first=String(as[`A${r+1}`]?.v||"");if(first.startsWith("LIDERANÇA:")){styleRange(as,`A${r+1}:P${r+1}`,section);as["!merges"].push({s:{r,c:0},e:{r,c:15}});}else{for(let c=0;c<16;c++){const a=XLSX.utils.encode_cell({r,c});if(as[a])as[a].s=cell;}textCols(as,r,[2,3,4,9,10,11,12]);}}as["!freeze"]={xSplit:0,ySplit:4};as["!autofilter"]={ref:`A4:P${Math.max(4,aData.length)}`};nav(as,"A2","← Voltar ao painel","PAINEL");add(as,"ATIVISTAS");
      const adData=[["ADMINISTRADORES"],["Administradores autorizados no sistema."],[""],["Nome completo","CPF","E-mail","Data do cadastro"],...db.admins.map(a=>[a.name,cpfBR(a.cpf),a.email,new Date(a.created).toLocaleString("pt-BR")])];const ad=XLSX.utils.aoa_to_sheet(adData);ad["!cols"]=[32,20,34,24].map(wch=>({wch}));ad["A1"].s=title;ad["A2"].s=subtitle;styleRange(ad,"A4:D4",header);for(let r=4;r<adData.length;r++){styleRange(ad,`A${r+1}:D${r+1}`,cell);textCols(ad,r,[1]);}ad["!freeze"]={xSplit:0,ySplit:4};ad["!autofilter"]={ref:`A4:D${Math.max(4,adData.length)}`};nav(ad,"A2","← Voltar ao painel","PAINEL");add(ad,"ADMINISTRADORES");
      const scData=[["ASSESSORIA"],["Contatos disponibilizados pela coordenação às lideranças."],[""],["Nome","Função / descrição","Telefone","E-mail","Observações"],...db.assessors.map(a=>[a.name,a.role,a.phone,a.email,a.notes])];const sc=XLSX.utils.aoa_to_sheet(scData);sc["!cols"]=[34,30,22,36,50].map(wch=>({wch}));sc["A1"].s=title;sc["A2"].s=subtitle;styleRange(sc,"A4:E4",header);for(let r=4;r<scData.length;r++)styleRange(sc,`A${r+1}:E${r+1}`,cell);sc["!freeze"]={xSplit:0,ySplit:4};sc["!autofilter"]={ref:`A4:E${Math.max(4,scData.length)}`};nav(sc,"A2","← Voltar ao painel","PAINEL");add(sc,"ASSESSORIA");
      XLSX.writeFile(wb,`cadastro-eleitoral-dainara-${new Date().toISOString().slice(0,10)}.xlsx`,{bookType:"xlsx",compression:true});setMsg("Excel exportado com painel, navegação, filtros e equipes separadas.");
    } catch(e) { console.error(e); setMsg("Não foi possível gerar o Excel. Tente novamente."); }
  };

  const exportCSV = () => { const h=["Liderança","Nome completo","Data de nascimento","CPF","Telefone","Endereço","Nome da mãe","E-mail","Bairro","CEP","Título de eleitor","Zona","Seção","Chave Pix","Titular Pix","Banco"];const rows=[];db.leaderships.forEach(l=>db.activists.filter(a=>a.leaderId===l.id).forEach(a=>rows.push([l.name,a.name,dateBR(a.birth),cpfBR(a.cpf),phoneBR(a.phone),a.address,a.mother,a.email,a.neighborhood,cepBR(a.cep),a.title,a.zone,a.section,a.pix,a.pixname,a.bank])));const csv=[h,...rows].map(r=>r.map(v=>`"${String(v??"").replace(/"/g,'""')}"`).join(";")).join("\r\n");const blob=new Blob(["\uFEFF"+csv],{type:"text/csv;charset=utf-8"});const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download=`cadastro-eleitoral-dainara-${new Date().toISOString().slice(0,10)}.csv`;a.click();URL.revokeObjectURL(url);setMsg("CSV exportado."); };

  if(mode==="home") return <main className="shell"><section className="hero"><b>Cadastro Eleitoral</b><h1>Coordenadora Dainara Torres</h1><p>Portal de acesso, cadastro e gestão de lideranças e ativistas.</p><div className="actions"><button onClick={()=>go("leader-access")}>Já sou liderança</button><button onClick={()=>go("leader-release")}>Se torne liderança</button><button className="outline" onClick={()=>go("admin-access")}>Acesso administrativo</button><button className="outline" onClick={()=>go("admin-release")}>Se tornar administrador</button></div><div className="home-note">Dados persistidos neste navegador durante a fase de teste.</div></section></main>;
  if(["leader-access","admin-access","leader-release","admin-release"].includes(mode)){const admin=mode.includes("admin"),rel=mode.includes("release");return <Access admin={admin} release={rel} cpf={cpf} setCpf={setCpf} password={password} setPassword={setPassword} code={code} setCode={setCode} msg={msg} onBack={()=>go("home")} onEnter={()=>rel?release(admin):(admin?enterAdmin():enterLeader())} onSwitch={()=>go(rel?(admin?"admin-access":"leader-access"):(admin?"admin-release":"leader-release"))}/>;}
  if(mode==="admin-reg") return <AdminReg back={()=>go("admin-area")} save={saveAdmin} msg={msg}/>;
  if(mode==="leader-reg") return <Form kind="liderança" f={f} setF={setF} save={saveLeader} back={()=>go(returnTo)} msg={msg} edit={Boolean(editing)} admin={false} leaderships={db.leaderships} leaderId={leaderId} setLeaderId={setLeaderId}/>;
  if(mode==="leader-credentials") return <Credential person={generatedPerson} password={generatedPassword} onAccess={()=>{setRole("leader");setLeaderId(generatedPerson?.id||null);setView("dashboard");go("leader-area");}} onBack={()=>go("home")}/>;
  if(mode==="leader-form") return <Form kind="liderança" f={f} setF={setF} save={saveLeader} back={()=>go(returnTo)} msg={msg} edit={Boolean(editing)} admin={role==="admin"} leaderships={db.leaderships} leaderId={leaderId} setLeaderId={setLeaderId}/>;
  if(mode==="activist-form") return <Form kind="ativista" f={f} setF={setF} save={saveAct} back={()=>go(returnTo)} msg={msg} edit={Boolean(editing)} admin={role==="admin"} leaderships={db.leaderships} leaderId={leaderId} setLeaderId={setLeaderId}/>;

  const admin=role==="admin", areaMode=admin?"admin-area":"leader-area";
  if(mode!==areaMode){ go(areaMode); return null; }
  const title=admin?"Área Administrativa":`Olá, ${leader?.name||"Liderança"}`;
  let content=null;
  if(view==="dashboard") content=admin?<><div className="cards"><div className="metric"><div className="label">Lideranças</div><div className="value">{db.leaderships.length}</div></div><div className="metric"><div className="label">Ativistas</div><div className="value">{db.activists.length}</div></div><div className="metric"><div className="label">Administradores</div><div className="value">{db.admins.length}</div></div><div className="metric"><div className="label">Assessoria</div><div className="value">{db.assessors.length}</div></div></div><div className="quick-grid"><button className="quick" onClick={()=>setView("leaderships")}><b>♙ Lideranças</b><span>Visualizar e gerenciar todas as lideranças.</span></button><button className="quick" onClick={()=>setView("activists")}><b>♧ Ativistas</b><span>Consultar ativistas e suas lideranças responsáveis.</span></button><button className="quick" onClick={()=>setView("assessors")}><b>☎ Assessoria</b><span>Adicionar e editar os contatos mostrados às lideranças.</span></button><button className="quick" onClick={()=>go("admin-release")}><b>＋ Novo administrador</b><span>Liberar um novo cadastro com o código de teste.</span></button></div><div className="panel"><div className="page-head"><div><h2>Visão geral</h2><p>Gerencie os cadastros e mantenha as equipes separadas por liderança.</p></div><button className="primary" onClick={startL}>＋ Nova liderança</button></div></div><ManausCoverageMap db={db}/></> : <><div className="cards"><div className="metric"><div className="label">Meus ativistas</div><div className="value">{mine.length}</div></div><div className="metric"><div className="label">Meu cadastro</div><div className="value">✓</div></div></div><div className="quick-grid"><button className="quick" onClick={()=>setView("activists")}><b>♧ Meus ativistas</b><span>Veja somente os ativistas vinculados à sua liderança.</span></button><button className="quick" onClick={()=>startA()}><b>＋ Adicionar ativista</b><span>Cadastre um novo ativista vinculado a você.</span></button><button className="quick" onClick={()=>setView("profile")}><b>👤 Meu cadastro</b><span>Consulte e edite seus próprios dados.</span></button><button className="quick" onClick={()=>setView("assessors")}><b>☎ Assessoria</b><span>Veja os contatos disponibilizados pela coordenação.</span></button><button className="quick" onClick={async()=>{const link=window.location.origin + "/familia?lideranca=" + encodeURIComponent(leaderId||"");try{await navigator.clipboard.writeText(link);setMsg("Link da Rede de confiança copiado. Compartilhe-o com os ativistas da sua liderança.");}catch{setMsg("Não foi possível copiar o link automaticamente.");}}}><b>♡ Copiar link da Rede de confiança</b><span>Compartilhe este link com os ativistas vinculados à sua liderança.</span></button></div></>;
  else if(view==="leaderships"&&admin) content=<div className="panel"><div className="page-head"><div><h2>Lideranças</h2><p>Todas as lideranças cadastradas pela coordenação.</p></div><button className="primary" onClick={startL}>＋ Nova liderança</button></div><input className="search" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Pesquisar por nome, CPF ou título..."/>{leaders.length?leaders.map(l=><div className="list-item clickable" key={l.id} onClick={()=>{setDetail(l.id);setView("leadership-detail")}}><div><b>{l.name}</b><small>{cpfBR(l.cpf)} • Título {l.title}</small></div><span>{db.activists.filter(a=>a.leaderId===l.id).length} ativista(s) →</span></div>):<div className="empty">Nenhuma liderança encontrada.</div>}</div>;
  else if(view==="activists"){const list=admin?acts:mine.filter(a=>`${a.name} ${a.cpf} ${a.title}`.toLowerCase().includes(search.toLowerCase()));content=<div className="panel"><div className="page-head"><div><h2>{admin?"Ativistas":"Meus ativistas"}</h2><p>{admin?"A liderança aparece em cada linha para não misturar equipes.":`Liderança: ${leader?.name||"não cadastrada"}`}</p></div><button className="primary" onClick={()=>startA()}>＋ Adicionar ativista</button></div><input className="search" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Pesquisar por nome, CPF ou título..."/>{list.length?list.map(a=>{const l=db.leaderships.find(x=>x.id===a.leaderId);return <div className="list-item clickable activist-row" key={a.id} onClick={()=>{setDetail(a.id);setView("activist-detail")}}><div><b>{a.name}</b><small>{cpfBR(a.cpf)} • Título {a.title}</small></div><span className="leader-tag">👤 {l?.name||"Sem liderança"}</span></div>}):<div className="empty">Nenhum ativista encontrado.</div>}</div>}
  else if(view==="leadership-detail"&&admin){const l=db.leaderships.find(x=>x.id===detail),team=db.activists.filter(x=>x.leaderId===detail);content=<Detail title="Liderança" person={l} onBack={()=>setView("leaderships")} onEdit={()=>edit(l,"leader")} credential={<AdminLeadershipCredential person={l} onReset={() => { const password = makePassword(); setDb((d) => ({ ...d, leaderships: d.leaderships.map((item) => item.id === l.id ? { ...item, password, updated: Date.now() } : item) })); setMsg("Nova senha gerada. Copie-a e entregue à liderança."); return password; }} />} team={<div className="panel team-panel"><div className="page-head"><div><h3>Ativistas vinculados: {team.length}</h3><p>Equipe delimitada para facilitar a gestão.</p></div><button className="primary" onClick={()=>startA(l?.id)}>＋ Adicionar ativista</button></div>{team.length?team.map(a=><div className="list-item clickable" key={a.id} onClick={()=>{setDetail(a.id);setView("activist-detail")}}><div><b>{a.name}</b><small>{cpfBR(a.cpf)} • Título {a.title}</small></div><span>Ver cadastro →</span></div>):<div className="empty">Nenhum ativista vinculado.</div>}</div>}/>}
  else if(view==="activist-detail"){const a=db.activists.find(x=>x.id===detail),l=db.leaderships.find(x=>x.id===a?.leaderId);content=<Detail title="Cadastro do ativista" person={a} leader={l?.name} onBack={()=>setView("activists")} onEdit={()=>edit(a,"activist")}/>;}
  else if(view==="profile"&&!admin) content=<Detail title="Meu cadastro" person={leader} onBack={()=>setView("dashboard")} onEdit={()=>leader&&edit(leader,"leader")}/>;
  else if(view==="assessors"&&admin) content=<div className="panel"><div className="page-head"><div><h2>Contatos da assessoria</h2><p>Cadastre aqui os contatos que aparecerão automaticamente na Área da Liderança.</p></div><button type="button" className="primary" onClick={() => { setMsg(""); setEditingAssessor(null); setAssessorForm({ ...EMPTY_ASSESSOR }); setAssessorEditorOpen(true); setView("assessors"); }}>＋ Adicionar contato</button></div>{assessorEditorOpen&&<div className="assessor-modal-backdrop" role="dialog" aria-modal="true"><div className="assessor-modal"><AssessorForm form={assessorForm} setForm={setAssessorForm} save={saveAssessor} cancel={cancelAssessor} editing={editingAssessor}/></div></div>} {!assessorEditorOpen&&!db.assessors.length&&<div className="empty assessor-empty">Nenhum contato cadastrado. Clique em <b>“Adicionar contato”</b> para incluir o primeiro.</div>}{db.assessors.map(a=><div className="assessor-admin-row" key={a.id}><div className="assessor-info"><b>{a.name}</b>{a.role&&<small>{a.role}</small>}{a.phone&&<span>☎ {a.phone}</span>}{a.email&&<span>✉ {a.email}</span>}{a.notes&&<em>{a.notes}</em>}</div><div className="assessor-actions"><button className="outline" onClick={()=>editAssessor(a)}>Editar</button><button className="danger" onClick={()=>removeAssessor(a.id)}>Excluir</button></div></div>)}</div>;
  else if(view==="assessors"&&!admin) content=<div className="panel"><h2>Contatos da assessoria</h2><p>Contatos disponibilizados pela coordenação.</p>{!db.assessors.length?<div className="empty">Nenhum contato da assessoria foi cadastrado ainda.</div>:db.assessors.map(a=><div className="contact-card" key={a.id}><b>{a.name}</b>{a.role&&<strong>{a.role}</strong>}{a.phone&&<span>☎ {a.phone}</span>}{a.email&&<span>✉ {a.email}</span>}{a.notes&&<span>{a.notes}</span>}</div>)}</div>;
  else if(view==="admins"&&admin) content=<div className="panel"><div className="page-head"><h2>Administradores</h2><button className="primary" onClick={()=>go("admin-release")}>＋ Novo administrador</button></div>{db.admins.length?db.admins.map(a=><div className="list-item" key={a.id}><div><b>{a.name}</b><small>{cpfBR(a.cpf)} • {a.email||"Sem e-mail"}</small></div><span>{new Date(a.created).toLocaleDateString("pt-BR")}</span></div>):<div className="empty">Nenhum administrador cadastrado.</div>}</div>;
  else content=<div className="panel empty">Selecione uma opção no menu.</div>;

  return <div className="app-shell"><Side admin={admin} view={view} setView={v=>{setSearch("");setDetail(null);setView(v)}} logout={logout} newL={startL} newA={()=>startA()} exportExcel={exportExcel} exportCSV={exportCSV}/><div className="main"><header className="topbar"><div><h1>{title}</h1><p>{admin?"Visão geral dos cadastros e equipes.":"Gerencie somente os ativistas vinculados à sua liderança."}</p></div>{admin&&<div style={{display:"flex",gap:10,flexWrap:"wrap"}}><button className="outline top-export" onClick={exportExcel}>⇩ Exportar Excel</button><button className="outline top-export" onClick={exportCSV}>⇩ Exportar CSV</button></div>}</header><main className="content">{msg&&<div className="result">{msg}</div>}{content}</main></div></div>;
}
